<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido\CalcularFreteRequest;

/**
 * Protobuf type <code>freterapido.CalcularFreteRequest.Filtro</code>
 */
class Filtro
{
    /**
     * Generated from protobuf enum <code>FILTRO_SEM_FILTRO = 0;</code>
     */
    const FILTRO_SEM_FILTRO = 0;
    /**
     * Generated from protobuf enum <code>FILTRO_MENOR_PRECO = 1;</code>
     */
    const FILTRO_MENOR_PRECO = 1;
    /**
     * Generated from protobuf enum <code>FILTRO_MENOR_PRAZO = 2;</code>
     */
    const FILTRO_MENOR_PRAZO = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Filtro::class, \Freterapido\CalcularFreteRequest_Filtro::class);

