<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido\CalcularFreteRequest;

/**
 * Protobuf type <code>freterapido.CalcularFreteRequest.TipoCobranca</code>
 */
class TipoCobranca
{
    /**
     * Generated from protobuf enum <code>TIPOCOBRANCA_UNKNOWN = 0;</code>
     */
    const TIPOCOBRANCA_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>TIPOCOBRANCA_CIF = 1;</code>
     */
    const TIPOCOBRANCA_CIF = 1;
    /**
     * Generated from protobuf enum <code>TIPOCOBRANCA_FOB = 2;</code>
     */
    const TIPOCOBRANCA_FOB = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TipoCobranca::class, \Freterapido\CalcularFreteRequest_TipoCobranca::class);

