/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.freterapido.DestinatarioRequest');
goog.provide('proto.freterapido.DestinatarioRequest.TipoPessoa');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.freterapido.Endereco');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.freterapido.DestinatarioRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.freterapido.DestinatarioRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.freterapido.DestinatarioRequest.displayName = 'proto.freterapido.DestinatarioRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.freterapido.DestinatarioRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.freterapido.DestinatarioRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.freterapido.DestinatarioRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.freterapido.DestinatarioRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tipoPessoa: jspb.Message.getFieldWithDefault(msg, 1, 0),
    cnpjCpf: jspb.Message.getFieldWithDefault(msg, 2, ""),
    inscricaoEstadual: jspb.Message.getFieldWithDefault(msg, 3, ""),
    endereco: (f = msg.getEndereco()) && proto.freterapido.Endereco.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.freterapido.DestinatarioRequest}
 */
proto.freterapido.DestinatarioRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.freterapido.DestinatarioRequest;
  return proto.freterapido.DestinatarioRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.freterapido.DestinatarioRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.freterapido.DestinatarioRequest}
 */
proto.freterapido.DestinatarioRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.freterapido.DestinatarioRequest.TipoPessoa} */ (reader.readEnum());
      msg.setTipoPessoa(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCnpjCpf(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setInscricaoEstadual(value);
      break;
    case 4:
      var value = new proto.freterapido.Endereco;
      reader.readMessage(value,proto.freterapido.Endereco.deserializeBinaryFromReader);
      msg.setEndereco(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.freterapido.DestinatarioRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.freterapido.DestinatarioRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.freterapido.DestinatarioRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.freterapido.DestinatarioRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTipoPessoa();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCnpjCpf();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getInscricaoEstadual();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEndereco();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.freterapido.Endereco.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.freterapido.DestinatarioRequest.TipoPessoa = {
  TIPOPESSOA_UNKNOWN: 0,
  TIPOPESSOA_FISICA: 1,
  TIPOPESSOA_JURIDICA: 2
};

/**
 * optional TipoPessoa tipo_pessoa = 1;
 * @return {!proto.freterapido.DestinatarioRequest.TipoPessoa}
 */
proto.freterapido.DestinatarioRequest.prototype.getTipoPessoa = function() {
  return /** @type {!proto.freterapido.DestinatarioRequest.TipoPessoa} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.freterapido.DestinatarioRequest.TipoPessoa} value */
proto.freterapido.DestinatarioRequest.prototype.setTipoPessoa = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string cnpj_cpf = 2;
 * @return {string}
 */
proto.freterapido.DestinatarioRequest.prototype.getCnpjCpf = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.freterapido.DestinatarioRequest.prototype.setCnpjCpf = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string inscricao_estadual = 3;
 * @return {string}
 */
proto.freterapido.DestinatarioRequest.prototype.getInscricaoEstadual = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.freterapido.DestinatarioRequest.prototype.setInscricaoEstadual = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Endereco endereco = 4;
 * @return {?proto.freterapido.Endereco}
 */
proto.freterapido.DestinatarioRequest.prototype.getEndereco = function() {
  return /** @type{?proto.freterapido.Endereco} */ (
    jspb.Message.getWrapperField(this, proto.freterapido.Endereco, 4));
};


/** @param {?proto.freterapido.Endereco|undefined} value */
proto.freterapido.DestinatarioRequest.prototype.setEndereco = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.freterapido.DestinatarioRequest.prototype.clearEndereco = function() {
  this.setEndereco(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.freterapido.DestinatarioRequest.prototype.hasEndereco = function() {
  return jspb.Message.getField(this, 4) != null;
};


