// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: freterapido.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Freterapido {

  /// <summary>Holder for reflection information generated from freterapido.proto</summary>
  public static partial class FreterapidoReflection {

    #region Descriptor
    /// <summary>File descriptor for freterapido.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FreterapidoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFmcmV0ZXJhcGlkby5wcm90bxILZnJldGVyYXBpZG8aHmdvb2dsZS9wcm90",
            "b2J1Zi93cmFwcGVycy5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFt",
            "cC5wcm90byL9BAoUQ2FsY3VsYXJGcmV0ZVJlcXVlc3QSRQoNdGlwb19jb2Jy",
            "YW5jYRgBIAEoDjIuLmZyZXRlcmFwaWRvLkNhbGN1bGFyRnJldGVSZXF1ZXN0",
            "LlRpcG9Db2JyYW5jYRI4CgZmaWx0cm8YAiABKA4yKC5mcmV0ZXJhcGlkby5D",
            "YWxjdWxhckZyZXRlUmVxdWVzdC5GaWx0cm8SKwoGbGltaXRlGAMgASgLMhsu",
            "Z29vZ2xlLnByb3RvYnVmLkludDY0VmFsdWUSDQoFdG9rZW4YBCABKAkSGQoR",
            "Y29kaWdvX3BsYXRhZm9ybWEYBSABKAkSHQoVcmV0b3JuYXJfY29uc29saWRh",
            "Y2FvGAYgASgIEjAKCXJlbWV0ZW50ZRgHIAEoCzIdLmZyZXRlcmFwaWRvLlJl",
            "bWV0ZW50ZVJlcXVlc3QSMAoJZXhwZWRpZG9yGAggASgLMh0uZnJldGVyYXBp",
            "ZG8uRXhwZWRpZG9yUmVxdWVzdBI2CgxkZXN0aW5hdGFyaW8YCSABKAsyIC5m",
            "cmV0ZXJhcGlkby5EZXN0aW5hdGFyaW9SZXF1ZXN0EisKB3ZvbHVtZXMYCiAD",
            "KAsyGi5mcmV0ZXJhcGlkby5Wb2x1bWVSZXF1ZXN0IlQKDFRpcG9Db2JyYW5j",
            "YRIYChRUSVBPQ09CUkFOQ0FfVU5LTk9XThAAEhQKEFRJUE9DT0JSQU5DQV9D",
            "SUYQARIUChBUSVBPQ09CUkFOQ0FfRk9CEAIiTwoGRmlsdHJvEhUKEUZJTFRS",
            "T19TRU1fRklMVFJPEAASFgoSRklMVFJPX01FTk9SX1BSRUNPEAESFgoSRklM",
            "VFJPX01FTk9SX1BSQVpPEAIiFwoIRW5kZXJlY28SCwoDY2VwGAEgASgJIiAK",
            "EFJlbWV0ZW50ZVJlcXVlc3QSDAoEY25wahgBIAEoCSI7ChBFeHBlZGlkb3JS",
            "ZXF1ZXN0EicKCGVuZGVyZWNvGAEgASgLMhUuZnJldGVyYXBpZG8uRW5kZXJl",
            "Y28ihAIKE0Rlc3RpbmF0YXJpb1JlcXVlc3QSQAoLdGlwb19wZXNzb2EYASAB",
            "KA4yKy5mcmV0ZXJhcGlkby5EZXN0aW5hdGFyaW9SZXF1ZXN0LlRpcG9QZXNz",
            "b2ESEAoIY25wal9jcGYYAiABKAkSGgoSaW5zY3JpY2FvX2VzdGFkdWFsGAMg",
            "ASgJEicKCGVuZGVyZWNvGAQgASgLMhUuZnJldGVyYXBpZG8uRW5kZXJlY28i",
            "VAoKVGlwb1Blc3NvYRIWChJUSVBPUEVTU09BX1VOS05PV04QABIVChFUSVBP",
            "UEVTU09BX0ZJU0lDQRABEhcKE1RJUE9QRVNTT0FfSlVSSURJQ0EQAiKxAgoN",
            "Vm9sdW1lUmVxdWVzdBIMCgR0aXBvGAEgASgFEikKA3NrdRgCIAEoCzIcLmdv",
            "b2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIvCglkZXNjcmljYW8YAyABKAsy",
            "HC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUSEgoKcXVhbnRpZGFkZRgE",
            "IAEoBRIOCgZhbHR1cmEYBSABKAESDwoHbGFyZ3VyYRgGIAEoARITCgtjb21w",
            "cmltZW50bxgHIAEoARIMCgRwZXNvGAggASgBEg0KBXZhbG9yGAkgASgBEhcK",
            "D3ZvbHVtZXNfcHJvZHV0bxgKIAEoBRISCgpjb25zb2xpZGFyGAsgASgIEhIK",
            "CnNvYnJlcG9zdG8YDCABKAgSDgoGdG9tYmFyGA0gASgIIpkBChVDYWxjdWxh",
            "ckZyZXRlUmVzcG9uc2USFAoMdG9rZW5fb2ZlcnRhGAEgASgJEjwKD3RyYW5z",
            "cG9ydGFkb3JhcxgCIAMoCzIjLmZyZXRlcmFwaWRvLlRyYW5zcG9ydGFkb3Jh",
            "UmVzcG9uc2USLAoHdm9sdW1lcxgDIAMoCzIbLmZyZXRlcmFwaWRvLlZvbHVt",
            "ZVJlc3BvbnNlIo8CChZUcmFuc3BvcnRhZG9yYVJlc3BvbnNlEg4KBm9mZXJ0",
            "YRgBIAEoAxIMCgRjbnBqGAIgASgJEhAKCGxvZ290aXBvGAMgASgJEgwKBG5v",
            "bWUYBCABKAkSDwoHc2VydmljbxgFIAEoCRI3ChFkZXNjcmljYW9fc2Vydmlj",
            "bxgGIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIVCg1wcmF6",
            "b19lbnRyZWdhGAcgASgFEiwKCHZhbGlkYWRlGAggASgLMhouZ29vZ2xlLnBy",
            "b3RvYnVmLlRpbWVzdGFtcBITCgtjdXN0b19mcmV0ZRgJIAEoARITCgtwcmVj",
            "b19mcmV0ZRgKIAEoASKmAgoOVm9sdW1lUmVzcG9uc2USDAoEdGlwbxgBIAEo",
            "BRIpCgNza3UYAiABKAsyHC5nb29nbGUucHJvdG9idWYuU3RyaW5nVmFsdWUS",
            "LwoJZGVzY3JpY2FvGAMgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1Zh",
            "bHVlEhIKCnF1YW50aWRhZGUYBCABKAUSDgoGYWx0dXJhGAUgASgBEg8KB2xh",
            "cmd1cmEYBiABKAESEwoLY29tcHJpbWVudG8YByABKAESDAoEcGVzbxgIIAEo",
            "ARINCgV2YWxvchgJIAEoARIXCg92b2x1bWVzX3Byb2R1dG8YCiABKAUSKgoF",
            "aXRlbXMYCyADKAsyGy5mcmV0ZXJhcGlkby5Wb2x1bWVSZXNwb25zZTJlCgtG",
            "cmV0ZVJhcGlkbxJWCg1DYWxjdWxhckZyZXRlEiEuZnJldGVyYXBpZG8uQ2Fs",
            "Y3VsYXJGcmV0ZVJlcXVlc3QaIi5mcmV0ZXJhcGlkby5DYWxjdWxhckZyZXRl",
            "UmVzcG9uc2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Freterapido.CalcularFreteRequest), global::Freterapido.CalcularFreteRequest.Parser, new[]{ "TipoCobranca", "Filtro", "Limite", "Token", "CodigoPlataforma", "RetornarConsolidacao", "Remetente", "Expedidor", "Destinatario", "Volumes" }, null, new[]{ typeof(global::Freterapido.CalcularFreteRequest.Types.TipoCobranca), typeof(global::Freterapido.CalcularFreteRequest.Types.Filtro) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Freterapido.Endereco), global::Freterapido.Endereco.Parser, new[]{ "Cep" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Freterapido.RemetenteRequest), global::Freterapido.RemetenteRequest.Parser, new[]{ "Cnpj" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Freterapido.ExpedidorRequest), global::Freterapido.ExpedidorRequest.Parser, new[]{ "Endereco" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Freterapido.DestinatarioRequest), global::Freterapido.DestinatarioRequest.Parser, new[]{ "TipoPessoa", "CnpjCpf", "InscricaoEstadual", "Endereco" }, null, new[]{ typeof(global::Freterapido.DestinatarioRequest.Types.TipoPessoa) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Freterapido.VolumeRequest), global::Freterapido.VolumeRequest.Parser, new[]{ "Tipo", "Sku", "Descricao", "Quantidade", "Altura", "Largura", "Comprimento", "Peso", "Valor", "VolumesProduto", "Consolidar", "Sobreposto", "Tombar" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Freterapido.CalcularFreteResponse), global::Freterapido.CalcularFreteResponse.Parser, new[]{ "TokenOferta", "Transportadoras", "Volumes" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Freterapido.TransportadoraResponse), global::Freterapido.TransportadoraResponse.Parser, new[]{ "Oferta", "Cnpj", "Logotipo", "Nome", "Servico", "DescricaoServico", "PrazoEntrega", "Validade", "CustoFrete", "PrecoFrete" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Freterapido.VolumeResponse), global::Freterapido.VolumeResponse.Parser, new[]{ "Tipo", "Sku", "Descricao", "Quantidade", "Altura", "Largura", "Comprimento", "Peso", "Valor", "VolumesProduto", "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CalcularFreteRequest : pb::IMessage<CalcularFreteRequest> {
    private static readonly pb::MessageParser<CalcularFreteRequest> _parser = new pb::MessageParser<CalcularFreteRequest>(() => new CalcularFreteRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CalcularFreteRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Freterapido.FreterapidoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CalcularFreteRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CalcularFreteRequest(CalcularFreteRequest other) : this() {
      tipoCobranca_ = other.tipoCobranca_;
      filtro_ = other.filtro_;
      Limite = other.Limite;
      token_ = other.token_;
      codigoPlataforma_ = other.codigoPlataforma_;
      retornarConsolidacao_ = other.retornarConsolidacao_;
      remetente_ = other.remetente_ != null ? other.remetente_.Clone() : null;
      expedidor_ = other.expedidor_ != null ? other.expedidor_.Clone() : null;
      destinatario_ = other.destinatario_ != null ? other.destinatario_.Clone() : null;
      volumes_ = other.volumes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CalcularFreteRequest Clone() {
      return new CalcularFreteRequest(this);
    }

    /// <summary>Field number for the "tipo_cobranca" field.</summary>
    public const int TipoCobrancaFieldNumber = 1;
    private global::Freterapido.CalcularFreteRequest.Types.TipoCobranca tipoCobranca_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Freterapido.CalcularFreteRequest.Types.TipoCobranca TipoCobranca {
      get { return tipoCobranca_; }
      set {
        tipoCobranca_ = value;
      }
    }

    /// <summary>Field number for the "filtro" field.</summary>
    public const int FiltroFieldNumber = 2;
    private global::Freterapido.CalcularFreteRequest.Types.Filtro filtro_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Freterapido.CalcularFreteRequest.Types.Filtro Filtro {
      get { return filtro_; }
      set {
        filtro_ = value;
      }
    }

    /// <summary>Field number for the "limite" field.</summary>
    public const int LimiteFieldNumber = 3;
    private static readonly pb::FieldCodec<long?> _single_limite_codec = pb::FieldCodec.ForStructWrapper<long>(26);
    private long? limite_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long? Limite {
      get { return limite_; }
      set {
        limite_ = value;
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 4;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "codigo_plataforma" field.</summary>
    public const int CodigoPlataformaFieldNumber = 5;
    private string codigoPlataforma_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodigoPlataforma {
      get { return codigoPlataforma_; }
      set {
        codigoPlataforma_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "retornar_consolidacao" field.</summary>
    public const int RetornarConsolidacaoFieldNumber = 6;
    private bool retornarConsolidacao_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool RetornarConsolidacao {
      get { return retornarConsolidacao_; }
      set {
        retornarConsolidacao_ = value;
      }
    }

    /// <summary>Field number for the "remetente" field.</summary>
    public const int RemetenteFieldNumber = 7;
    private global::Freterapido.RemetenteRequest remetente_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Freterapido.RemetenteRequest Remetente {
      get { return remetente_; }
      set {
        remetente_ = value;
      }
    }

    /// <summary>Field number for the "expedidor" field.</summary>
    public const int ExpedidorFieldNumber = 8;
    private global::Freterapido.ExpedidorRequest expedidor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Freterapido.ExpedidorRequest Expedidor {
      get { return expedidor_; }
      set {
        expedidor_ = value;
      }
    }

    /// <summary>Field number for the "destinatario" field.</summary>
    public const int DestinatarioFieldNumber = 9;
    private global::Freterapido.DestinatarioRequest destinatario_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Freterapido.DestinatarioRequest Destinatario {
      get { return destinatario_; }
      set {
        destinatario_ = value;
      }
    }

    /// <summary>Field number for the "volumes" field.</summary>
    public const int VolumesFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Freterapido.VolumeRequest> _repeated_volumes_codec
        = pb::FieldCodec.ForMessage(82, global::Freterapido.VolumeRequest.Parser);
    private readonly pbc::RepeatedField<global::Freterapido.VolumeRequest> volumes_ = new pbc::RepeatedField<global::Freterapido.VolumeRequest>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Freterapido.VolumeRequest> Volumes {
      get { return volumes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CalcularFreteRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CalcularFreteRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TipoCobranca != other.TipoCobranca) return false;
      if (Filtro != other.Filtro) return false;
      if (Limite != other.Limite) return false;
      if (Token != other.Token) return false;
      if (CodigoPlataforma != other.CodigoPlataforma) return false;
      if (RetornarConsolidacao != other.RetornarConsolidacao) return false;
      if (!object.Equals(Remetente, other.Remetente)) return false;
      if (!object.Equals(Expedidor, other.Expedidor)) return false;
      if (!object.Equals(Destinatario, other.Destinatario)) return false;
      if(!volumes_.Equals(other.volumes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TipoCobranca != 0) hash ^= TipoCobranca.GetHashCode();
      if (Filtro != 0) hash ^= Filtro.GetHashCode();
      if (limite_ != null) hash ^= Limite.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (CodigoPlataforma.Length != 0) hash ^= CodigoPlataforma.GetHashCode();
      if (RetornarConsolidacao != false) hash ^= RetornarConsolidacao.GetHashCode();
      if (remetente_ != null) hash ^= Remetente.GetHashCode();
      if (expedidor_ != null) hash ^= Expedidor.GetHashCode();
      if (destinatario_ != null) hash ^= Destinatario.GetHashCode();
      hash ^= volumes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TipoCobranca != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TipoCobranca);
      }
      if (Filtro != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Filtro);
      }
      if (limite_ != null) {
        _single_limite_codec.WriteTagAndValue(output, Limite);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Token);
      }
      if (CodigoPlataforma.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CodigoPlataforma);
      }
      if (RetornarConsolidacao != false) {
        output.WriteRawTag(48);
        output.WriteBool(RetornarConsolidacao);
      }
      if (remetente_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Remetente);
      }
      if (expedidor_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Expedidor);
      }
      if (destinatario_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Destinatario);
      }
      volumes_.WriteTo(output, _repeated_volumes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TipoCobranca != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TipoCobranca);
      }
      if (Filtro != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Filtro);
      }
      if (limite_ != null) {
        size += _single_limite_codec.CalculateSizeWithTag(Limite);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (CodigoPlataforma.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodigoPlataforma);
      }
      if (RetornarConsolidacao != false) {
        size += 1 + 1;
      }
      if (remetente_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Remetente);
      }
      if (expedidor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Expedidor);
      }
      if (destinatario_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Destinatario);
      }
      size += volumes_.CalculateSize(_repeated_volumes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CalcularFreteRequest other) {
      if (other == null) {
        return;
      }
      if (other.TipoCobranca != 0) {
        TipoCobranca = other.TipoCobranca;
      }
      if (other.Filtro != 0) {
        Filtro = other.Filtro;
      }
      if (other.limite_ != null) {
        if (limite_ == null || other.Limite != 0L) {
          Limite = other.Limite;
        }
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.CodigoPlataforma.Length != 0) {
        CodigoPlataforma = other.CodigoPlataforma;
      }
      if (other.RetornarConsolidacao != false) {
        RetornarConsolidacao = other.RetornarConsolidacao;
      }
      if (other.remetente_ != null) {
        if (remetente_ == null) {
          remetente_ = new global::Freterapido.RemetenteRequest();
        }
        Remetente.MergeFrom(other.Remetente);
      }
      if (other.expedidor_ != null) {
        if (expedidor_ == null) {
          expedidor_ = new global::Freterapido.ExpedidorRequest();
        }
        Expedidor.MergeFrom(other.Expedidor);
      }
      if (other.destinatario_ != null) {
        if (destinatario_ == null) {
          destinatario_ = new global::Freterapido.DestinatarioRequest();
        }
        Destinatario.MergeFrom(other.Destinatario);
      }
      volumes_.Add(other.volumes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            tipoCobranca_ = (global::Freterapido.CalcularFreteRequest.Types.TipoCobranca) input.ReadEnum();
            break;
          }
          case 16: {
            filtro_ = (global::Freterapido.CalcularFreteRequest.Types.Filtro) input.ReadEnum();
            break;
          }
          case 26: {
            long? value = _single_limite_codec.Read(input);
            if (limite_ == null || value != 0L) {
              Limite = value;
            }
            break;
          }
          case 34: {
            Token = input.ReadString();
            break;
          }
          case 42: {
            CodigoPlataforma = input.ReadString();
            break;
          }
          case 48: {
            RetornarConsolidacao = input.ReadBool();
            break;
          }
          case 58: {
            if (remetente_ == null) {
              remetente_ = new global::Freterapido.RemetenteRequest();
            }
            input.ReadMessage(remetente_);
            break;
          }
          case 66: {
            if (expedidor_ == null) {
              expedidor_ = new global::Freterapido.ExpedidorRequest();
            }
            input.ReadMessage(expedidor_);
            break;
          }
          case 74: {
            if (destinatario_ == null) {
              destinatario_ = new global::Freterapido.DestinatarioRequest();
            }
            input.ReadMessage(destinatario_);
            break;
          }
          case 82: {
            volumes_.AddEntriesFrom(input, _repeated_volumes_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the CalcularFreteRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum TipoCobranca {
        [pbr::OriginalName("TIPOCOBRANCA_UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("TIPOCOBRANCA_CIF")] Cif = 1,
        [pbr::OriginalName("TIPOCOBRANCA_FOB")] Fob = 2,
      }

      public enum Filtro {
        [pbr::OriginalName("FILTRO_SEM_FILTRO")] SemFiltro = 0,
        [pbr::OriginalName("FILTRO_MENOR_PRECO")] MenorPreco = 1,
        [pbr::OriginalName("FILTRO_MENOR_PRAZO")] MenorPrazo = 2,
      }

    }
    #endregion

  }

  public sealed partial class Endereco : pb::IMessage<Endereco> {
    private static readonly pb::MessageParser<Endereco> _parser = new pb::MessageParser<Endereco>(() => new Endereco());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Endereco> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Freterapido.FreterapidoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Endereco() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Endereco(Endereco other) : this() {
      cep_ = other.cep_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Endereco Clone() {
      return new Endereco(this);
    }

    /// <summary>Field number for the "cep" field.</summary>
    public const int CepFieldNumber = 1;
    private string cep_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Cep {
      get { return cep_; }
      set {
        cep_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Endereco);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Endereco other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cep != other.Cep) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Cep.Length != 0) hash ^= Cep.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Cep.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cep);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Cep.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cep);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Endereco other) {
      if (other == null) {
        return;
      }
      if (other.Cep.Length != 0) {
        Cep = other.Cep;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Cep = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RemetenteRequest : pb::IMessage<RemetenteRequest> {
    private static readonly pb::MessageParser<RemetenteRequest> _parser = new pb::MessageParser<RemetenteRequest>(() => new RemetenteRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RemetenteRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Freterapido.FreterapidoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemetenteRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemetenteRequest(RemetenteRequest other) : this() {
      cnpj_ = other.cnpj_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RemetenteRequest Clone() {
      return new RemetenteRequest(this);
    }

    /// <summary>Field number for the "cnpj" field.</summary>
    public const int CnpjFieldNumber = 1;
    private string cnpj_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Cnpj {
      get { return cnpj_; }
      set {
        cnpj_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RemetenteRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RemetenteRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cnpj != other.Cnpj) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Cnpj.Length != 0) hash ^= Cnpj.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Cnpj.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cnpj);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Cnpj.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cnpj);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RemetenteRequest other) {
      if (other == null) {
        return;
      }
      if (other.Cnpj.Length != 0) {
        Cnpj = other.Cnpj;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Cnpj = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ExpedidorRequest : pb::IMessage<ExpedidorRequest> {
    private static readonly pb::MessageParser<ExpedidorRequest> _parser = new pb::MessageParser<ExpedidorRequest>(() => new ExpedidorRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExpedidorRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Freterapido.FreterapidoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExpedidorRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExpedidorRequest(ExpedidorRequest other) : this() {
      endereco_ = other.endereco_ != null ? other.endereco_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExpedidorRequest Clone() {
      return new ExpedidorRequest(this);
    }

    /// <summary>Field number for the "endereco" field.</summary>
    public const int EnderecoFieldNumber = 1;
    private global::Freterapido.Endereco endereco_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Freterapido.Endereco Endereco {
      get { return endereco_; }
      set {
        endereco_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExpedidorRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExpedidorRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Endereco, other.Endereco)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (endereco_ != null) hash ^= Endereco.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (endereco_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Endereco);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (endereco_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Endereco);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExpedidorRequest other) {
      if (other == null) {
        return;
      }
      if (other.endereco_ != null) {
        if (endereco_ == null) {
          endereco_ = new global::Freterapido.Endereco();
        }
        Endereco.MergeFrom(other.Endereco);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (endereco_ == null) {
              endereco_ = new global::Freterapido.Endereco();
            }
            input.ReadMessage(endereco_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class DestinatarioRequest : pb::IMessage<DestinatarioRequest> {
    private static readonly pb::MessageParser<DestinatarioRequest> _parser = new pb::MessageParser<DestinatarioRequest>(() => new DestinatarioRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DestinatarioRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Freterapido.FreterapidoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DestinatarioRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DestinatarioRequest(DestinatarioRequest other) : this() {
      tipoPessoa_ = other.tipoPessoa_;
      cnpjCpf_ = other.cnpjCpf_;
      inscricaoEstadual_ = other.inscricaoEstadual_;
      endereco_ = other.endereco_ != null ? other.endereco_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DestinatarioRequest Clone() {
      return new DestinatarioRequest(this);
    }

    /// <summary>Field number for the "tipo_pessoa" field.</summary>
    public const int TipoPessoaFieldNumber = 1;
    private global::Freterapido.DestinatarioRequest.Types.TipoPessoa tipoPessoa_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Freterapido.DestinatarioRequest.Types.TipoPessoa TipoPessoa {
      get { return tipoPessoa_; }
      set {
        tipoPessoa_ = value;
      }
    }

    /// <summary>Field number for the "cnpj_cpf" field.</summary>
    public const int CnpjCpfFieldNumber = 2;
    private string cnpjCpf_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CnpjCpf {
      get { return cnpjCpf_; }
      set {
        cnpjCpf_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inscricao_estadual" field.</summary>
    public const int InscricaoEstadualFieldNumber = 3;
    private string inscricaoEstadual_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InscricaoEstadual {
      get { return inscricaoEstadual_; }
      set {
        inscricaoEstadual_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endereco" field.</summary>
    public const int EnderecoFieldNumber = 4;
    private global::Freterapido.Endereco endereco_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Freterapido.Endereco Endereco {
      get { return endereco_; }
      set {
        endereco_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DestinatarioRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DestinatarioRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TipoPessoa != other.TipoPessoa) return false;
      if (CnpjCpf != other.CnpjCpf) return false;
      if (InscricaoEstadual != other.InscricaoEstadual) return false;
      if (!object.Equals(Endereco, other.Endereco)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TipoPessoa != 0) hash ^= TipoPessoa.GetHashCode();
      if (CnpjCpf.Length != 0) hash ^= CnpjCpf.GetHashCode();
      if (InscricaoEstadual.Length != 0) hash ^= InscricaoEstadual.GetHashCode();
      if (endereco_ != null) hash ^= Endereco.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TipoPessoa != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) TipoPessoa);
      }
      if (CnpjCpf.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CnpjCpf);
      }
      if (InscricaoEstadual.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(InscricaoEstadual);
      }
      if (endereco_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Endereco);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TipoPessoa != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TipoPessoa);
      }
      if (CnpjCpf.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CnpjCpf);
      }
      if (InscricaoEstadual.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InscricaoEstadual);
      }
      if (endereco_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Endereco);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DestinatarioRequest other) {
      if (other == null) {
        return;
      }
      if (other.TipoPessoa != 0) {
        TipoPessoa = other.TipoPessoa;
      }
      if (other.CnpjCpf.Length != 0) {
        CnpjCpf = other.CnpjCpf;
      }
      if (other.InscricaoEstadual.Length != 0) {
        InscricaoEstadual = other.InscricaoEstadual;
      }
      if (other.endereco_ != null) {
        if (endereco_ == null) {
          endereco_ = new global::Freterapido.Endereco();
        }
        Endereco.MergeFrom(other.Endereco);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            tipoPessoa_ = (global::Freterapido.DestinatarioRequest.Types.TipoPessoa) input.ReadEnum();
            break;
          }
          case 18: {
            CnpjCpf = input.ReadString();
            break;
          }
          case 26: {
            InscricaoEstadual = input.ReadString();
            break;
          }
          case 34: {
            if (endereco_ == null) {
              endereco_ = new global::Freterapido.Endereco();
            }
            input.ReadMessage(endereco_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the DestinatarioRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum TipoPessoa {
        [pbr::OriginalName("TIPOPESSOA_UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("TIPOPESSOA_FISICA")] Fisica = 1,
        [pbr::OriginalName("TIPOPESSOA_JURIDICA")] Juridica = 2,
      }

    }
    #endregion

  }

  public sealed partial class VolumeRequest : pb::IMessage<VolumeRequest> {
    private static readonly pb::MessageParser<VolumeRequest> _parser = new pb::MessageParser<VolumeRequest>(() => new VolumeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VolumeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Freterapido.FreterapidoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VolumeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VolumeRequest(VolumeRequest other) : this() {
      tipo_ = other.tipo_;
      Sku = other.Sku;
      Descricao = other.Descricao;
      quantidade_ = other.quantidade_;
      altura_ = other.altura_;
      largura_ = other.largura_;
      comprimento_ = other.comprimento_;
      peso_ = other.peso_;
      valor_ = other.valor_;
      volumesProduto_ = other.volumesProduto_;
      consolidar_ = other.consolidar_;
      sobreposto_ = other.sobreposto_;
      tombar_ = other.tombar_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VolumeRequest Clone() {
      return new VolumeRequest(this);
    }

    /// <summary>Field number for the "tipo" field.</summary>
    public const int TipoFieldNumber = 1;
    private int tipo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Tipo {
      get { return tipo_; }
      set {
        tipo_ = value;
      }
    }

    /// <summary>Field number for the "sku" field.</summary>
    public const int SkuFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _single_sku_codec = pb::FieldCodec.ForClassWrapper<string>(18);
    private string sku_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sku {
      get { return sku_; }
      set {
        sku_ = value;
      }
    }

    /// <summary>Field number for the "descricao" field.</summary>
    public const int DescricaoFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _single_descricao_codec = pb::FieldCodec.ForClassWrapper<string>(26);
    private string descricao_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Descricao {
      get { return descricao_; }
      set {
        descricao_ = value;
      }
    }

    /// <summary>Field number for the "quantidade" field.</summary>
    public const int QuantidadeFieldNumber = 4;
    private int quantidade_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quantidade {
      get { return quantidade_; }
      set {
        quantidade_ = value;
      }
    }

    /// <summary>Field number for the "altura" field.</summary>
    public const int AlturaFieldNumber = 5;
    private double altura_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Altura {
      get { return altura_; }
      set {
        altura_ = value;
      }
    }

    /// <summary>Field number for the "largura" field.</summary>
    public const int LarguraFieldNumber = 6;
    private double largura_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Largura {
      get { return largura_; }
      set {
        largura_ = value;
      }
    }

    /// <summary>Field number for the "comprimento" field.</summary>
    public const int ComprimentoFieldNumber = 7;
    private double comprimento_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Comprimento {
      get { return comprimento_; }
      set {
        comprimento_ = value;
      }
    }

    /// <summary>Field number for the "peso" field.</summary>
    public const int PesoFieldNumber = 8;
    private double peso_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Peso {
      get { return peso_; }
      set {
        peso_ = value;
      }
    }

    /// <summary>Field number for the "valor" field.</summary>
    public const int ValorFieldNumber = 9;
    private double valor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Valor {
      get { return valor_; }
      set {
        valor_ = value;
      }
    }

    /// <summary>Field number for the "volumes_produto" field.</summary>
    public const int VolumesProdutoFieldNumber = 10;
    private int volumesProduto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int VolumesProduto {
      get { return volumesProduto_; }
      set {
        volumesProduto_ = value;
      }
    }

    /// <summary>Field number for the "consolidar" field.</summary>
    public const int ConsolidarFieldNumber = 11;
    private bool consolidar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Consolidar {
      get { return consolidar_; }
      set {
        consolidar_ = value;
      }
    }

    /// <summary>Field number for the "sobreposto" field.</summary>
    public const int SobrepostoFieldNumber = 12;
    private bool sobreposto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Sobreposto {
      get { return sobreposto_; }
      set {
        sobreposto_ = value;
      }
    }

    /// <summary>Field number for the "tombar" field.</summary>
    public const int TombarFieldNumber = 13;
    private bool tombar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Tombar {
      get { return tombar_; }
      set {
        tombar_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VolumeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VolumeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Tipo != other.Tipo) return false;
      if (Sku != other.Sku) return false;
      if (Descricao != other.Descricao) return false;
      if (Quantidade != other.Quantidade) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Altura, other.Altura)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Largura, other.Largura)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Comprimento, other.Comprimento)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Peso, other.Peso)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Valor, other.Valor)) return false;
      if (VolumesProduto != other.VolumesProduto) return false;
      if (Consolidar != other.Consolidar) return false;
      if (Sobreposto != other.Sobreposto) return false;
      if (Tombar != other.Tombar) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Tipo != 0) hash ^= Tipo.GetHashCode();
      if (sku_ != null) hash ^= Sku.GetHashCode();
      if (descricao_ != null) hash ^= Descricao.GetHashCode();
      if (Quantidade != 0) hash ^= Quantidade.GetHashCode();
      if (Altura != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Altura);
      if (Largura != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Largura);
      if (Comprimento != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Comprimento);
      if (Peso != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Peso);
      if (Valor != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Valor);
      if (VolumesProduto != 0) hash ^= VolumesProduto.GetHashCode();
      if (Consolidar != false) hash ^= Consolidar.GetHashCode();
      if (Sobreposto != false) hash ^= Sobreposto.GetHashCode();
      if (Tombar != false) hash ^= Tombar.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Tipo != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Tipo);
      }
      if (sku_ != null) {
        _single_sku_codec.WriteTagAndValue(output, Sku);
      }
      if (descricao_ != null) {
        _single_descricao_codec.WriteTagAndValue(output, Descricao);
      }
      if (Quantidade != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Quantidade);
      }
      if (Altura != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Altura);
      }
      if (Largura != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Largura);
      }
      if (Comprimento != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Comprimento);
      }
      if (Peso != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Peso);
      }
      if (Valor != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Valor);
      }
      if (VolumesProduto != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(VolumesProduto);
      }
      if (Consolidar != false) {
        output.WriteRawTag(88);
        output.WriteBool(Consolidar);
      }
      if (Sobreposto != false) {
        output.WriteRawTag(96);
        output.WriteBool(Sobreposto);
      }
      if (Tombar != false) {
        output.WriteRawTag(104);
        output.WriteBool(Tombar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Tipo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Tipo);
      }
      if (sku_ != null) {
        size += _single_sku_codec.CalculateSizeWithTag(Sku);
      }
      if (descricao_ != null) {
        size += _single_descricao_codec.CalculateSizeWithTag(Descricao);
      }
      if (Quantidade != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quantidade);
      }
      if (Altura != 0D) {
        size += 1 + 8;
      }
      if (Largura != 0D) {
        size += 1 + 8;
      }
      if (Comprimento != 0D) {
        size += 1 + 8;
      }
      if (Peso != 0D) {
        size += 1 + 8;
      }
      if (Valor != 0D) {
        size += 1 + 8;
      }
      if (VolumesProduto != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VolumesProduto);
      }
      if (Consolidar != false) {
        size += 1 + 1;
      }
      if (Sobreposto != false) {
        size += 1 + 1;
      }
      if (Tombar != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VolumeRequest other) {
      if (other == null) {
        return;
      }
      if (other.Tipo != 0) {
        Tipo = other.Tipo;
      }
      if (other.sku_ != null) {
        if (sku_ == null || other.Sku != "") {
          Sku = other.Sku;
        }
      }
      if (other.descricao_ != null) {
        if (descricao_ == null || other.Descricao != "") {
          Descricao = other.Descricao;
        }
      }
      if (other.Quantidade != 0) {
        Quantidade = other.Quantidade;
      }
      if (other.Altura != 0D) {
        Altura = other.Altura;
      }
      if (other.Largura != 0D) {
        Largura = other.Largura;
      }
      if (other.Comprimento != 0D) {
        Comprimento = other.Comprimento;
      }
      if (other.Peso != 0D) {
        Peso = other.Peso;
      }
      if (other.Valor != 0D) {
        Valor = other.Valor;
      }
      if (other.VolumesProduto != 0) {
        VolumesProduto = other.VolumesProduto;
      }
      if (other.Consolidar != false) {
        Consolidar = other.Consolidar;
      }
      if (other.Sobreposto != false) {
        Sobreposto = other.Sobreposto;
      }
      if (other.Tombar != false) {
        Tombar = other.Tombar;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Tipo = input.ReadInt32();
            break;
          }
          case 18: {
            string value = _single_sku_codec.Read(input);
            if (sku_ == null || value != "") {
              Sku = value;
            }
            break;
          }
          case 26: {
            string value = _single_descricao_codec.Read(input);
            if (descricao_ == null || value != "") {
              Descricao = value;
            }
            break;
          }
          case 32: {
            Quantidade = input.ReadInt32();
            break;
          }
          case 41: {
            Altura = input.ReadDouble();
            break;
          }
          case 49: {
            Largura = input.ReadDouble();
            break;
          }
          case 57: {
            Comprimento = input.ReadDouble();
            break;
          }
          case 65: {
            Peso = input.ReadDouble();
            break;
          }
          case 73: {
            Valor = input.ReadDouble();
            break;
          }
          case 80: {
            VolumesProduto = input.ReadInt32();
            break;
          }
          case 88: {
            Consolidar = input.ReadBool();
            break;
          }
          case 96: {
            Sobreposto = input.ReadBool();
            break;
          }
          case 104: {
            Tombar = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CalcularFreteResponse : pb::IMessage<CalcularFreteResponse> {
    private static readonly pb::MessageParser<CalcularFreteResponse> _parser = new pb::MessageParser<CalcularFreteResponse>(() => new CalcularFreteResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CalcularFreteResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Freterapido.FreterapidoReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CalcularFreteResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CalcularFreteResponse(CalcularFreteResponse other) : this() {
      tokenOferta_ = other.tokenOferta_;
      transportadoras_ = other.transportadoras_.Clone();
      volumes_ = other.volumes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CalcularFreteResponse Clone() {
      return new CalcularFreteResponse(this);
    }

    /// <summary>Field number for the "token_oferta" field.</summary>
    public const int TokenOfertaFieldNumber = 1;
    private string tokenOferta_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TokenOferta {
      get { return tokenOferta_; }
      set {
        tokenOferta_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "transportadoras" field.</summary>
    public const int TransportadorasFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Freterapido.TransportadoraResponse> _repeated_transportadoras_codec
        = pb::FieldCodec.ForMessage(18, global::Freterapido.TransportadoraResponse.Parser);
    private readonly pbc::RepeatedField<global::Freterapido.TransportadoraResponse> transportadoras_ = new pbc::RepeatedField<global::Freterapido.TransportadoraResponse>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Freterapido.TransportadoraResponse> Transportadoras {
      get { return transportadoras_; }
    }

    /// <summary>Field number for the "volumes" field.</summary>
    public const int VolumesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Freterapido.VolumeResponse> _repeated_volumes_codec
        = pb::FieldCodec.ForMessage(26, global::Freterapido.VolumeResponse.Parser);
    private readonly pbc::RepeatedField<global::Freterapido.VolumeResponse> volumes_ = new pbc::RepeatedField<global::Freterapido.VolumeResponse>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Freterapido.VolumeResponse> Volumes {
      get { return volumes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CalcularFreteResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CalcularFreteResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TokenOferta != other.TokenOferta) return false;
      if(!transportadoras_.Equals(other.transportadoras_)) return false;
      if(!volumes_.Equals(other.volumes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TokenOferta.Length != 0) hash ^= TokenOferta.GetHashCode();
      hash ^= transportadoras_.GetHashCode();
      hash ^= volumes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TokenOferta.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TokenOferta);
      }
      transportadoras_.WriteTo(output, _repeated_transportadoras_codec);
      volumes_.WriteTo(output, _repeated_volumes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TokenOferta.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TokenOferta);
      }
      size += transportadoras_.CalculateSize(_repeated_transportadoras_codec);
      size += volumes_.CalculateSize(_repeated_volumes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CalcularFreteResponse other) {
      if (other == null) {
        return;
      }
      if (other.TokenOferta.Length != 0) {
        TokenOferta = other.TokenOferta;
      }
      transportadoras_.Add(other.transportadoras_);
      volumes_.Add(other.volumes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TokenOferta = input.ReadString();
            break;
          }
          case 18: {
            transportadoras_.AddEntriesFrom(input, _repeated_transportadoras_codec);
            break;
          }
          case 26: {
            volumes_.AddEntriesFrom(input, _repeated_volumes_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class TransportadoraResponse : pb::IMessage<TransportadoraResponse> {
    private static readonly pb::MessageParser<TransportadoraResponse> _parser = new pb::MessageParser<TransportadoraResponse>(() => new TransportadoraResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TransportadoraResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Freterapido.FreterapidoReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransportadoraResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransportadoraResponse(TransportadoraResponse other) : this() {
      oferta_ = other.oferta_;
      cnpj_ = other.cnpj_;
      logotipo_ = other.logotipo_;
      nome_ = other.nome_;
      servico_ = other.servico_;
      DescricaoServico = other.DescricaoServico;
      prazoEntrega_ = other.prazoEntrega_;
      validade_ = other.validade_ != null ? other.validade_.Clone() : null;
      custoFrete_ = other.custoFrete_;
      precoFrete_ = other.precoFrete_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransportadoraResponse Clone() {
      return new TransportadoraResponse(this);
    }

    /// <summary>Field number for the "oferta" field.</summary>
    public const int OfertaFieldNumber = 1;
    private long oferta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Oferta {
      get { return oferta_; }
      set {
        oferta_ = value;
      }
    }

    /// <summary>Field number for the "cnpj" field.</summary>
    public const int CnpjFieldNumber = 2;
    private string cnpj_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Cnpj {
      get { return cnpj_; }
      set {
        cnpj_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "logotipo" field.</summary>
    public const int LogotipoFieldNumber = 3;
    private string logotipo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Logotipo {
      get { return logotipo_; }
      set {
        logotipo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nome" field.</summary>
    public const int NomeFieldNumber = 4;
    private string nome_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nome {
      get { return nome_; }
      set {
        nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "servico" field.</summary>
    public const int ServicoFieldNumber = 5;
    private string servico_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Servico {
      get { return servico_; }
      set {
        servico_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "descricao_servico" field.</summary>
    public const int DescricaoServicoFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _single_descricaoServico_codec = pb::FieldCodec.ForClassWrapper<string>(50);
    private string descricaoServico_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DescricaoServico {
      get { return descricaoServico_; }
      set {
        descricaoServico_ = value;
      }
    }

    /// <summary>Field number for the "prazo_entrega" field.</summary>
    public const int PrazoEntregaFieldNumber = 7;
    private int prazoEntrega_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PrazoEntrega {
      get { return prazoEntrega_; }
      set {
        prazoEntrega_ = value;
      }
    }

    /// <summary>Field number for the "validade" field.</summary>
    public const int ValidadeFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp validade_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Validade {
      get { return validade_; }
      set {
        validade_ = value;
      }
    }

    /// <summary>Field number for the "custo_frete" field.</summary>
    public const int CustoFreteFieldNumber = 9;
    private double custoFrete_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double CustoFrete {
      get { return custoFrete_; }
      set {
        custoFrete_ = value;
      }
    }

    /// <summary>Field number for the "preco_frete" field.</summary>
    public const int PrecoFreteFieldNumber = 10;
    private double precoFrete_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double PrecoFrete {
      get { return precoFrete_; }
      set {
        precoFrete_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TransportadoraResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TransportadoraResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Oferta != other.Oferta) return false;
      if (Cnpj != other.Cnpj) return false;
      if (Logotipo != other.Logotipo) return false;
      if (Nome != other.Nome) return false;
      if (Servico != other.Servico) return false;
      if (DescricaoServico != other.DescricaoServico) return false;
      if (PrazoEntrega != other.PrazoEntrega) return false;
      if (!object.Equals(Validade, other.Validade)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(CustoFrete, other.CustoFrete)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PrecoFrete, other.PrecoFrete)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Oferta != 0L) hash ^= Oferta.GetHashCode();
      if (Cnpj.Length != 0) hash ^= Cnpj.GetHashCode();
      if (Logotipo.Length != 0) hash ^= Logotipo.GetHashCode();
      if (Nome.Length != 0) hash ^= Nome.GetHashCode();
      if (Servico.Length != 0) hash ^= Servico.GetHashCode();
      if (descricaoServico_ != null) hash ^= DescricaoServico.GetHashCode();
      if (PrazoEntrega != 0) hash ^= PrazoEntrega.GetHashCode();
      if (validade_ != null) hash ^= Validade.GetHashCode();
      if (CustoFrete != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(CustoFrete);
      if (PrecoFrete != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PrecoFrete);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Oferta != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Oferta);
      }
      if (Cnpj.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Cnpj);
      }
      if (Logotipo.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Logotipo);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Nome);
      }
      if (Servico.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Servico);
      }
      if (descricaoServico_ != null) {
        _single_descricaoServico_codec.WriteTagAndValue(output, DescricaoServico);
      }
      if (PrazoEntrega != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(PrazoEntrega);
      }
      if (validade_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Validade);
      }
      if (CustoFrete != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(CustoFrete);
      }
      if (PrecoFrete != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(PrecoFrete);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Oferta != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Oferta);
      }
      if (Cnpj.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cnpj);
      }
      if (Logotipo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Logotipo);
      }
      if (Nome.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
      }
      if (Servico.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Servico);
      }
      if (descricaoServico_ != null) {
        size += _single_descricaoServico_codec.CalculateSizeWithTag(DescricaoServico);
      }
      if (PrazoEntrega != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PrazoEntrega);
      }
      if (validade_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Validade);
      }
      if (CustoFrete != 0D) {
        size += 1 + 8;
      }
      if (PrecoFrete != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TransportadoraResponse other) {
      if (other == null) {
        return;
      }
      if (other.Oferta != 0L) {
        Oferta = other.Oferta;
      }
      if (other.Cnpj.Length != 0) {
        Cnpj = other.Cnpj;
      }
      if (other.Logotipo.Length != 0) {
        Logotipo = other.Logotipo;
      }
      if (other.Nome.Length != 0) {
        Nome = other.Nome;
      }
      if (other.Servico.Length != 0) {
        Servico = other.Servico;
      }
      if (other.descricaoServico_ != null) {
        if (descricaoServico_ == null || other.DescricaoServico != "") {
          DescricaoServico = other.DescricaoServico;
        }
      }
      if (other.PrazoEntrega != 0) {
        PrazoEntrega = other.PrazoEntrega;
      }
      if (other.validade_ != null) {
        if (validade_ == null) {
          validade_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Validade.MergeFrom(other.Validade);
      }
      if (other.CustoFrete != 0D) {
        CustoFrete = other.CustoFrete;
      }
      if (other.PrecoFrete != 0D) {
        PrecoFrete = other.PrecoFrete;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Oferta = input.ReadInt64();
            break;
          }
          case 18: {
            Cnpj = input.ReadString();
            break;
          }
          case 26: {
            Logotipo = input.ReadString();
            break;
          }
          case 34: {
            Nome = input.ReadString();
            break;
          }
          case 42: {
            Servico = input.ReadString();
            break;
          }
          case 50: {
            string value = _single_descricaoServico_codec.Read(input);
            if (descricaoServico_ == null || value != "") {
              DescricaoServico = value;
            }
            break;
          }
          case 56: {
            PrazoEntrega = input.ReadInt32();
            break;
          }
          case 66: {
            if (validade_ == null) {
              validade_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(validade_);
            break;
          }
          case 73: {
            CustoFrete = input.ReadDouble();
            break;
          }
          case 81: {
            PrecoFrete = input.ReadDouble();
            break;
          }
        }
      }
    }

  }

  public sealed partial class VolumeResponse : pb::IMessage<VolumeResponse> {
    private static readonly pb::MessageParser<VolumeResponse> _parser = new pb::MessageParser<VolumeResponse>(() => new VolumeResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VolumeResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Freterapido.FreterapidoReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VolumeResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VolumeResponse(VolumeResponse other) : this() {
      tipo_ = other.tipo_;
      Sku = other.Sku;
      Descricao = other.Descricao;
      quantidade_ = other.quantidade_;
      altura_ = other.altura_;
      largura_ = other.largura_;
      comprimento_ = other.comprimento_;
      peso_ = other.peso_;
      valor_ = other.valor_;
      volumesProduto_ = other.volumesProduto_;
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VolumeResponse Clone() {
      return new VolumeResponse(this);
    }

    /// <summary>Field number for the "tipo" field.</summary>
    public const int TipoFieldNumber = 1;
    private int tipo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Tipo {
      get { return tipo_; }
      set {
        tipo_ = value;
      }
    }

    /// <summary>Field number for the "sku" field.</summary>
    public const int SkuFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _single_sku_codec = pb::FieldCodec.ForClassWrapper<string>(18);
    private string sku_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sku {
      get { return sku_; }
      set {
        sku_ = value;
      }
    }

    /// <summary>Field number for the "descricao" field.</summary>
    public const int DescricaoFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _single_descricao_codec = pb::FieldCodec.ForClassWrapper<string>(26);
    private string descricao_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Descricao {
      get { return descricao_; }
      set {
        descricao_ = value;
      }
    }

    /// <summary>Field number for the "quantidade" field.</summary>
    public const int QuantidadeFieldNumber = 4;
    private int quantidade_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quantidade {
      get { return quantidade_; }
      set {
        quantidade_ = value;
      }
    }

    /// <summary>Field number for the "altura" field.</summary>
    public const int AlturaFieldNumber = 5;
    private double altura_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Altura {
      get { return altura_; }
      set {
        altura_ = value;
      }
    }

    /// <summary>Field number for the "largura" field.</summary>
    public const int LarguraFieldNumber = 6;
    private double largura_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Largura {
      get { return largura_; }
      set {
        largura_ = value;
      }
    }

    /// <summary>Field number for the "comprimento" field.</summary>
    public const int ComprimentoFieldNumber = 7;
    private double comprimento_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Comprimento {
      get { return comprimento_; }
      set {
        comprimento_ = value;
      }
    }

    /// <summary>Field number for the "peso" field.</summary>
    public const int PesoFieldNumber = 8;
    private double peso_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Peso {
      get { return peso_; }
      set {
        peso_ = value;
      }
    }

    /// <summary>Field number for the "valor" field.</summary>
    public const int ValorFieldNumber = 9;
    private double valor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Valor {
      get { return valor_; }
      set {
        valor_ = value;
      }
    }

    /// <summary>Field number for the "volumes_produto" field.</summary>
    public const int VolumesProdutoFieldNumber = 10;
    private int volumesProduto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int VolumesProduto {
      get { return volumesProduto_; }
      set {
        volumesProduto_ = value;
      }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 11;
    private static readonly pb::FieldCodec<global::Freterapido.VolumeResponse> _repeated_items_codec
        = pb::FieldCodec.ForMessage(90, global::Freterapido.VolumeResponse.Parser);
    private readonly pbc::RepeatedField<global::Freterapido.VolumeResponse> items_ = new pbc::RepeatedField<global::Freterapido.VolumeResponse>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Freterapido.VolumeResponse> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VolumeResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VolumeResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Tipo != other.Tipo) return false;
      if (Sku != other.Sku) return false;
      if (Descricao != other.Descricao) return false;
      if (Quantidade != other.Quantidade) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Altura, other.Altura)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Largura, other.Largura)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Comprimento, other.Comprimento)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Peso, other.Peso)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Valor, other.Valor)) return false;
      if (VolumesProduto != other.VolumesProduto) return false;
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Tipo != 0) hash ^= Tipo.GetHashCode();
      if (sku_ != null) hash ^= Sku.GetHashCode();
      if (descricao_ != null) hash ^= Descricao.GetHashCode();
      if (Quantidade != 0) hash ^= Quantidade.GetHashCode();
      if (Altura != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Altura);
      if (Largura != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Largura);
      if (Comprimento != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Comprimento);
      if (Peso != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Peso);
      if (Valor != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Valor);
      if (VolumesProduto != 0) hash ^= VolumesProduto.GetHashCode();
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Tipo != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Tipo);
      }
      if (sku_ != null) {
        _single_sku_codec.WriteTagAndValue(output, Sku);
      }
      if (descricao_ != null) {
        _single_descricao_codec.WriteTagAndValue(output, Descricao);
      }
      if (Quantidade != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Quantidade);
      }
      if (Altura != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Altura);
      }
      if (Largura != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Largura);
      }
      if (Comprimento != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Comprimento);
      }
      if (Peso != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Peso);
      }
      if (Valor != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Valor);
      }
      if (VolumesProduto != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(VolumesProduto);
      }
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Tipo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Tipo);
      }
      if (sku_ != null) {
        size += _single_sku_codec.CalculateSizeWithTag(Sku);
      }
      if (descricao_ != null) {
        size += _single_descricao_codec.CalculateSizeWithTag(Descricao);
      }
      if (Quantidade != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quantidade);
      }
      if (Altura != 0D) {
        size += 1 + 8;
      }
      if (Largura != 0D) {
        size += 1 + 8;
      }
      if (Comprimento != 0D) {
        size += 1 + 8;
      }
      if (Peso != 0D) {
        size += 1 + 8;
      }
      if (Valor != 0D) {
        size += 1 + 8;
      }
      if (VolumesProduto != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VolumesProduto);
      }
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VolumeResponse other) {
      if (other == null) {
        return;
      }
      if (other.Tipo != 0) {
        Tipo = other.Tipo;
      }
      if (other.sku_ != null) {
        if (sku_ == null || other.Sku != "") {
          Sku = other.Sku;
        }
      }
      if (other.descricao_ != null) {
        if (descricao_ == null || other.Descricao != "") {
          Descricao = other.Descricao;
        }
      }
      if (other.Quantidade != 0) {
        Quantidade = other.Quantidade;
      }
      if (other.Altura != 0D) {
        Altura = other.Altura;
      }
      if (other.Largura != 0D) {
        Largura = other.Largura;
      }
      if (other.Comprimento != 0D) {
        Comprimento = other.Comprimento;
      }
      if (other.Peso != 0D) {
        Peso = other.Peso;
      }
      if (other.Valor != 0D) {
        Valor = other.Valor;
      }
      if (other.VolumesProduto != 0) {
        VolumesProduto = other.VolumesProduto;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Tipo = input.ReadInt32();
            break;
          }
          case 18: {
            string value = _single_sku_codec.Read(input);
            if (sku_ == null || value != "") {
              Sku = value;
            }
            break;
          }
          case 26: {
            string value = _single_descricao_codec.Read(input);
            if (descricao_ == null || value != "") {
              Descricao = value;
            }
            break;
          }
          case 32: {
            Quantidade = input.ReadInt32();
            break;
          }
          case 41: {
            Altura = input.ReadDouble();
            break;
          }
          case 49: {
            Largura = input.ReadDouble();
            break;
          }
          case 57: {
            Comprimento = input.ReadDouble();
            break;
          }
          case 65: {
            Peso = input.ReadDouble();
            break;
          }
          case 73: {
            Valor = input.ReadDouble();
            break;
          }
          case 80: {
            VolumesProduto = input.ReadInt32();
            break;
          }
          case 90: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
