// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: freterapido.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DestinatarioRequest;
@class Endereco;
@class ExpedidorRequest;
@class GPBInt64Value;
@class GPBStringValue;
@class GPBTimestamp;
@class RemetenteRequest;
@class TransportadoraResponse;
@class VolumeRequest;
@class VolumeResponse;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CalcularFreteRequest_TipoCobranca

typedef GPB_ENUM(CalcularFreteRequest_TipoCobranca) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  CalcularFreteRequest_TipoCobranca_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  CalcularFreteRequest_TipoCobranca_TipocobrancaUnknown = 0,
  CalcularFreteRequest_TipoCobranca_TipocobrancaCif = 1,
  CalcularFreteRequest_TipoCobranca_TipocobrancaFob = 2,
};

GPBEnumDescriptor *CalcularFreteRequest_TipoCobranca_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CalcularFreteRequest_TipoCobranca_IsValidValue(int32_t value);

#pragma mark - Enum CalcularFreteRequest_Filtro

typedef GPB_ENUM(CalcularFreteRequest_Filtro) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  CalcularFreteRequest_Filtro_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  CalcularFreteRequest_Filtro_FiltroSemFiltro = 0,
  CalcularFreteRequest_Filtro_FiltroMenorPreco = 1,
  CalcularFreteRequest_Filtro_FiltroMenorPrazo = 2,
};

GPBEnumDescriptor *CalcularFreteRequest_Filtro_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CalcularFreteRequest_Filtro_IsValidValue(int32_t value);

#pragma mark - Enum DestinatarioRequest_TipoPessoa

typedef GPB_ENUM(DestinatarioRequest_TipoPessoa) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  DestinatarioRequest_TipoPessoa_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  DestinatarioRequest_TipoPessoa_TipopessoaUnknown = 0,
  DestinatarioRequest_TipoPessoa_TipopessoaFisica = 1,
  DestinatarioRequest_TipoPessoa_TipopessoaJuridica = 2,
};

GPBEnumDescriptor *DestinatarioRequest_TipoPessoa_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL DestinatarioRequest_TipoPessoa_IsValidValue(int32_t value);

#pragma mark - FreterapidoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface FreterapidoRoot : GPBRootObject
@end

#pragma mark - CalcularFreteRequest

typedef GPB_ENUM(CalcularFreteRequest_FieldNumber) {
  CalcularFreteRequest_FieldNumber_TipoCobranca = 1,
  CalcularFreteRequest_FieldNumber_Filtro = 2,
  CalcularFreteRequest_FieldNumber_Limite = 3,
  CalcularFreteRequest_FieldNumber_Token = 4,
  CalcularFreteRequest_FieldNumber_CodigoPlataforma = 5,
  CalcularFreteRequest_FieldNumber_RetornarConsolidacao = 6,
  CalcularFreteRequest_FieldNumber_Remetente = 7,
  CalcularFreteRequest_FieldNumber_Expedidor = 8,
  CalcularFreteRequest_FieldNumber_Destinatario = 9,
  CalcularFreteRequest_FieldNumber_VolumesArray = 10,
};

@interface CalcularFreteRequest : GPBMessage

@property(nonatomic, readwrite) CalcularFreteRequest_TipoCobranca tipoCobranca;

@property(nonatomic, readwrite) CalcularFreteRequest_Filtro filtro;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Value *limite;
/** Test to see if @c limite has been set. */
@property(nonatomic, readwrite) BOOL hasLimite;

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *codigoPlataforma;

@property(nonatomic, readwrite) BOOL retornarConsolidacao;

@property(nonatomic, readwrite, strong, null_resettable) RemetenteRequest *remetente;
/** Test to see if @c remetente has been set. */
@property(nonatomic, readwrite) BOOL hasRemetente;

@property(nonatomic, readwrite, strong, null_resettable) ExpedidorRequest *expedidor;
/** Test to see if @c expedidor has been set. */
@property(nonatomic, readwrite) BOOL hasExpedidor;

@property(nonatomic, readwrite, strong, null_resettable) DestinatarioRequest *destinatario;
/** Test to see if @c destinatario has been set. */
@property(nonatomic, readwrite) BOOL hasDestinatario;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<VolumeRequest*> *volumesArray;
/** The number of items in @c volumesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger volumesArray_Count;

@end

/**
 * Fetches the raw value of a @c CalcularFreteRequest's @c tipoCobranca property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t CalcularFreteRequest_TipoCobranca_RawValue(CalcularFreteRequest *message);
/**
 * Sets the raw value of an @c CalcularFreteRequest's @c tipoCobranca property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetCalcularFreteRequest_TipoCobranca_RawValue(CalcularFreteRequest *message, int32_t value);

/**
 * Fetches the raw value of a @c CalcularFreteRequest's @c filtro property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t CalcularFreteRequest_Filtro_RawValue(CalcularFreteRequest *message);
/**
 * Sets the raw value of an @c CalcularFreteRequest's @c filtro property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetCalcularFreteRequest_Filtro_RawValue(CalcularFreteRequest *message, int32_t value);

#pragma mark - Endereco

typedef GPB_ENUM(Endereco_FieldNumber) {
  Endereco_FieldNumber_Cep = 1,
};

@interface Endereco : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cep;

@end

#pragma mark - RemetenteRequest

typedef GPB_ENUM(RemetenteRequest_FieldNumber) {
  RemetenteRequest_FieldNumber_Cnpj = 1,
};

@interface RemetenteRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cnpj;

@end

#pragma mark - ExpedidorRequest

typedef GPB_ENUM(ExpedidorRequest_FieldNumber) {
  ExpedidorRequest_FieldNumber_Endereco = 1,
};

@interface ExpedidorRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Endereco *endereco;
/** Test to see if @c endereco has been set. */
@property(nonatomic, readwrite) BOOL hasEndereco;

@end

#pragma mark - DestinatarioRequest

typedef GPB_ENUM(DestinatarioRequest_FieldNumber) {
  DestinatarioRequest_FieldNumber_TipoPessoa = 1,
  DestinatarioRequest_FieldNumber_CnpjCpf = 2,
  DestinatarioRequest_FieldNumber_InscricaoEstadual = 3,
  DestinatarioRequest_FieldNumber_Endereco = 4,
};

@interface DestinatarioRequest : GPBMessage

@property(nonatomic, readwrite) DestinatarioRequest_TipoPessoa tipoPessoa;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cnpjCpf;

@property(nonatomic, readwrite, copy, null_resettable) NSString *inscricaoEstadual;

@property(nonatomic, readwrite, strong, null_resettable) Endereco *endereco;
/** Test to see if @c endereco has been set. */
@property(nonatomic, readwrite) BOOL hasEndereco;

@end

/**
 * Fetches the raw value of a @c DestinatarioRequest's @c tipoPessoa property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t DestinatarioRequest_TipoPessoa_RawValue(DestinatarioRequest *message);
/**
 * Sets the raw value of an @c DestinatarioRequest's @c tipoPessoa property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetDestinatarioRequest_TipoPessoa_RawValue(DestinatarioRequest *message, int32_t value);

#pragma mark - VolumeRequest

typedef GPB_ENUM(VolumeRequest_FieldNumber) {
  VolumeRequest_FieldNumber_Tipo = 1,
  VolumeRequest_FieldNumber_Sku = 2,
  VolumeRequest_FieldNumber_Descricao = 3,
  VolumeRequest_FieldNumber_Quantidade = 4,
  VolumeRequest_FieldNumber_Altura = 5,
  VolumeRequest_FieldNumber_Largura = 6,
  VolumeRequest_FieldNumber_Comprimento = 7,
  VolumeRequest_FieldNumber_Peso = 8,
  VolumeRequest_FieldNumber_Valor = 9,
  VolumeRequest_FieldNumber_VolumesProduto = 10,
  VolumeRequest_FieldNumber_Consolidar = 11,
  VolumeRequest_FieldNumber_Sobreposto = 12,
  VolumeRequest_FieldNumber_Tombar = 13,
};

@interface VolumeRequest : GPBMessage

@property(nonatomic, readwrite) int32_t tipo;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *sku;
/** Test to see if @c sku has been set. */
@property(nonatomic, readwrite) BOOL hasSku;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *descricao;
/** Test to see if @c descricao has been set. */
@property(nonatomic, readwrite) BOOL hasDescricao;

@property(nonatomic, readwrite) int32_t quantidade;

@property(nonatomic, readwrite) double altura;

@property(nonatomic, readwrite) double largura;

@property(nonatomic, readwrite) double comprimento;

@property(nonatomic, readwrite) double peso;

@property(nonatomic, readwrite) double valor;

@property(nonatomic, readwrite) int32_t volumesProduto;

@property(nonatomic, readwrite) BOOL consolidar;

@property(nonatomic, readwrite) BOOL sobreposto;

@property(nonatomic, readwrite) BOOL tombar;

@end

#pragma mark - CalcularFreteResponse

typedef GPB_ENUM(CalcularFreteResponse_FieldNumber) {
  CalcularFreteResponse_FieldNumber_TokenOferta = 1,
  CalcularFreteResponse_FieldNumber_TransportadorasArray = 2,
  CalcularFreteResponse_FieldNumber_VolumesArray = 3,
};

@interface CalcularFreteResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *tokenOferta;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransportadoraResponse*> *transportadorasArray;
/** The number of items in @c transportadorasArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transportadorasArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<VolumeResponse*> *volumesArray;
/** The number of items in @c volumesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger volumesArray_Count;

@end

#pragma mark - TransportadoraResponse

typedef GPB_ENUM(TransportadoraResponse_FieldNumber) {
  TransportadoraResponse_FieldNumber_Oferta = 1,
  TransportadoraResponse_FieldNumber_Cnpj = 2,
  TransportadoraResponse_FieldNumber_Logotipo = 3,
  TransportadoraResponse_FieldNumber_Nome = 4,
  TransportadoraResponse_FieldNumber_Servico = 5,
  TransportadoraResponse_FieldNumber_DescricaoServico = 6,
  TransportadoraResponse_FieldNumber_PrazoEntrega = 7,
  TransportadoraResponse_FieldNumber_Validade = 8,
  TransportadoraResponse_FieldNumber_CustoFrete = 9,
  TransportadoraResponse_FieldNumber_PrecoFrete = 10,
};

@interface TransportadoraResponse : GPBMessage

@property(nonatomic, readwrite) int64_t oferta;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cnpj;

@property(nonatomic, readwrite, copy, null_resettable) NSString *logotipo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nome;

@property(nonatomic, readwrite, copy, null_resettable) NSString *servico;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *descricaoServico;
/** Test to see if @c descricaoServico has been set. */
@property(nonatomic, readwrite) BOOL hasDescricaoServico;

@property(nonatomic, readwrite) int32_t prazoEntrega;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *validade;
/** Test to see if @c validade has been set. */
@property(nonatomic, readwrite) BOOL hasValidade;

@property(nonatomic, readwrite) double custoFrete;

@property(nonatomic, readwrite) double precoFrete;

@end

#pragma mark - VolumeResponse

typedef GPB_ENUM(VolumeResponse_FieldNumber) {
  VolumeResponse_FieldNumber_Tipo = 1,
  VolumeResponse_FieldNumber_Sku = 2,
  VolumeResponse_FieldNumber_Descricao = 3,
  VolumeResponse_FieldNumber_Quantidade = 4,
  VolumeResponse_FieldNumber_Altura = 5,
  VolumeResponse_FieldNumber_Largura = 6,
  VolumeResponse_FieldNumber_Comprimento = 7,
  VolumeResponse_FieldNumber_Peso = 8,
  VolumeResponse_FieldNumber_Valor = 9,
  VolumeResponse_FieldNumber_VolumesProduto = 10,
  VolumeResponse_FieldNumber_ItemsArray = 11,
};

@interface VolumeResponse : GPBMessage

@property(nonatomic, readwrite) int32_t tipo;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *sku;
/** Test to see if @c sku has been set. */
@property(nonatomic, readwrite) BOOL hasSku;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *descricao;
/** Test to see if @c descricao has been set. */
@property(nonatomic, readwrite) BOOL hasDescricao;

@property(nonatomic, readwrite) int32_t quantidade;

@property(nonatomic, readwrite) double altura;

@property(nonatomic, readwrite) double largura;

@property(nonatomic, readwrite) double comprimento;

@property(nonatomic, readwrite) double peso;

@property(nonatomic, readwrite) double valor;

@property(nonatomic, readwrite) int32_t volumesProduto;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<VolumeResponse*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
