<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido\DestinatarioRequest;

/**
 * Protobuf type <code>freterapido.DestinatarioRequest.TipoPessoa</code>
 */
class TipoPessoa
{
    /**
     * Generated from protobuf enum <code>TIPOPESSOA_UNKNOWN = 0;</code>
     */
    const TIPOPESSOA_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>TIPOPESSOA_FISICA = 1;</code>
     */
    const TIPOPESSOA_FISICA = 1;
    /**
     * Generated from protobuf enum <code>TIPOPESSOA_JURIDICA = 2;</code>
     */
    const TIPOPESSOA_JURIDICA = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TipoPessoa::class, \Freterapido\DestinatarioRequest_TipoPessoa::class);

