// Code generated by protoc-gen-go. DO NOT EDIT.
// source: freterapido.proto

package freterapido

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CalcularFreteRequest_TipoCobranca int32

const (
	CalcularFreteRequest_TIPOCOBRANCA_UNKNOWN CalcularFreteRequest_TipoCobranca = 0
	CalcularFreteRequest_TIPOCOBRANCA_CIF     CalcularFreteRequest_TipoCobranca = 1
	CalcularFreteRequest_TIPOCOBRANCA_FOB     CalcularFreteRequest_TipoCobranca = 2
)

var CalcularFreteRequest_TipoCobranca_name = map[int32]string{
	0: "TIPOCOBRANCA_UNKNOWN",
	1: "TIPOCOBRANCA_CIF",
	2: "TIPOCOBRANCA_FOB",
}

var CalcularFreteRequest_TipoCobranca_value = map[string]int32{
	"TIPOCOBRANCA_UNKNOWN": 0,
	"TIPOCOBRANCA_CIF":     1,
	"TIPOCOBRANCA_FOB":     2,
}

func (x CalcularFreteRequest_TipoCobranca) String() string {
	return proto.EnumName(CalcularFreteRequest_TipoCobranca_name, int32(x))
}

func (CalcularFreteRequest_TipoCobranca) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{0, 0}
}

type CalcularFreteRequest_Filtro int32

const (
	CalcularFreteRequest_FILTRO_SEM_FILTRO  CalcularFreteRequest_Filtro = 0
	CalcularFreteRequest_FILTRO_MENOR_PRECO CalcularFreteRequest_Filtro = 1
	CalcularFreteRequest_FILTRO_MENOR_PRAZO CalcularFreteRequest_Filtro = 2
)

var CalcularFreteRequest_Filtro_name = map[int32]string{
	0: "FILTRO_SEM_FILTRO",
	1: "FILTRO_MENOR_PRECO",
	2: "FILTRO_MENOR_PRAZO",
}

var CalcularFreteRequest_Filtro_value = map[string]int32{
	"FILTRO_SEM_FILTRO":  0,
	"FILTRO_MENOR_PRECO": 1,
	"FILTRO_MENOR_PRAZO": 2,
}

func (x CalcularFreteRequest_Filtro) String() string {
	return proto.EnumName(CalcularFreteRequest_Filtro_name, int32(x))
}

func (CalcularFreteRequest_Filtro) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{0, 1}
}

type DestinatarioRequest_TipoPessoa int32

const (
	DestinatarioRequest_TIPOPESSOA_UNKNOWN  DestinatarioRequest_TipoPessoa = 0
	DestinatarioRequest_TIPOPESSOA_FISICA   DestinatarioRequest_TipoPessoa = 1
	DestinatarioRequest_TIPOPESSOA_JURIDICA DestinatarioRequest_TipoPessoa = 2
)

var DestinatarioRequest_TipoPessoa_name = map[int32]string{
	0: "TIPOPESSOA_UNKNOWN",
	1: "TIPOPESSOA_FISICA",
	2: "TIPOPESSOA_JURIDICA",
}

var DestinatarioRequest_TipoPessoa_value = map[string]int32{
	"TIPOPESSOA_UNKNOWN":  0,
	"TIPOPESSOA_FISICA":   1,
	"TIPOPESSOA_JURIDICA": 2,
}

func (x DestinatarioRequest_TipoPessoa) String() string {
	return proto.EnumName(DestinatarioRequest_TipoPessoa_name, int32(x))
}

func (DestinatarioRequest_TipoPessoa) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{4, 0}
}

type CalcularFreteRequest struct {
	TipoCobranca         CalcularFreteRequest_TipoCobranca `protobuf:"varint,1,opt,name=tipo_cobranca,json=tipoCobranca,proto3,enum=freterapido.CalcularFreteRequest_TipoCobranca" json:"tipo_cobranca,omitempty"`
	Filtro               CalcularFreteRequest_Filtro       `protobuf:"varint,2,opt,name=filtro,proto3,enum=freterapido.CalcularFreteRequest_Filtro" json:"filtro,omitempty"`
	Limite               *wrappers.Int64Value              `protobuf:"bytes,3,opt,name=limite,proto3" json:"limite,omitempty"`
	Token                string                            `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	CodigoPlataforma     string                            `protobuf:"bytes,5,opt,name=codigo_plataforma,json=codigoPlataforma,proto3" json:"codigo_plataforma,omitempty"`
	RetornarConsolidacao bool                              `protobuf:"varint,6,opt,name=retornar_consolidacao,json=retornarConsolidacao,proto3" json:"retornar_consolidacao,omitempty"`
	Remetente            *RemetenteRequest                 `protobuf:"bytes,7,opt,name=remetente,proto3" json:"remetente,omitempty"`
	Expedidor            *ExpedidorRequest                 `protobuf:"bytes,8,opt,name=expedidor,proto3" json:"expedidor,omitempty"`
	Destinatario         *DestinatarioRequest              `protobuf:"bytes,9,opt,name=destinatario,proto3" json:"destinatario,omitempty"`
	Volumes              []*VolumeRequest                  `protobuf:"bytes,10,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CalcularFreteRequest) Reset()         { *m = CalcularFreteRequest{} }
func (m *CalcularFreteRequest) String() string { return proto.CompactTextString(m) }
func (*CalcularFreteRequest) ProtoMessage()    {}
func (*CalcularFreteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{0}
}

func (m *CalcularFreteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcularFreteRequest.Unmarshal(m, b)
}
func (m *CalcularFreteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcularFreteRequest.Marshal(b, m, deterministic)
}
func (m *CalcularFreteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcularFreteRequest.Merge(m, src)
}
func (m *CalcularFreteRequest) XXX_Size() int {
	return xxx_messageInfo_CalcularFreteRequest.Size(m)
}
func (m *CalcularFreteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcularFreteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalcularFreteRequest proto.InternalMessageInfo

func (m *CalcularFreteRequest) GetTipoCobranca() CalcularFreteRequest_TipoCobranca {
	if m != nil {
		return m.TipoCobranca
	}
	return CalcularFreteRequest_TIPOCOBRANCA_UNKNOWN
}

func (m *CalcularFreteRequest) GetFiltro() CalcularFreteRequest_Filtro {
	if m != nil {
		return m.Filtro
	}
	return CalcularFreteRequest_FILTRO_SEM_FILTRO
}

func (m *CalcularFreteRequest) GetLimite() *wrappers.Int64Value {
	if m != nil {
		return m.Limite
	}
	return nil
}

func (m *CalcularFreteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CalcularFreteRequest) GetCodigoPlataforma() string {
	if m != nil {
		return m.CodigoPlataforma
	}
	return ""
}

func (m *CalcularFreteRequest) GetRetornarConsolidacao() bool {
	if m != nil {
		return m.RetornarConsolidacao
	}
	return false
}

func (m *CalcularFreteRequest) GetRemetente() *RemetenteRequest {
	if m != nil {
		return m.Remetente
	}
	return nil
}

func (m *CalcularFreteRequest) GetExpedidor() *ExpedidorRequest {
	if m != nil {
		return m.Expedidor
	}
	return nil
}

func (m *CalcularFreteRequest) GetDestinatario() *DestinatarioRequest {
	if m != nil {
		return m.Destinatario
	}
	return nil
}

func (m *CalcularFreteRequest) GetVolumes() []*VolumeRequest {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type Endereco struct {
	Cep                  string   `protobuf:"bytes,1,opt,name=cep,proto3" json:"cep,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endereco) Reset()         { *m = Endereco{} }
func (m *Endereco) String() string { return proto.CompactTextString(m) }
func (*Endereco) ProtoMessage()    {}
func (*Endereco) Descriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{1}
}

func (m *Endereco) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endereco.Unmarshal(m, b)
}
func (m *Endereco) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endereco.Marshal(b, m, deterministic)
}
func (m *Endereco) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endereco.Merge(m, src)
}
func (m *Endereco) XXX_Size() int {
	return xxx_messageInfo_Endereco.Size(m)
}
func (m *Endereco) XXX_DiscardUnknown() {
	xxx_messageInfo_Endereco.DiscardUnknown(m)
}

var xxx_messageInfo_Endereco proto.InternalMessageInfo

func (m *Endereco) GetCep() string {
	if m != nil {
		return m.Cep
	}
	return ""
}

type RemetenteRequest struct {
	Cnpj                 string   `protobuf:"bytes,1,opt,name=cnpj,proto3" json:"cnpj,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemetenteRequest) Reset()         { *m = RemetenteRequest{} }
func (m *RemetenteRequest) String() string { return proto.CompactTextString(m) }
func (*RemetenteRequest) ProtoMessage()    {}
func (*RemetenteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{2}
}

func (m *RemetenteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemetenteRequest.Unmarshal(m, b)
}
func (m *RemetenteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemetenteRequest.Marshal(b, m, deterministic)
}
func (m *RemetenteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemetenteRequest.Merge(m, src)
}
func (m *RemetenteRequest) XXX_Size() int {
	return xxx_messageInfo_RemetenteRequest.Size(m)
}
func (m *RemetenteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemetenteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemetenteRequest proto.InternalMessageInfo

func (m *RemetenteRequest) GetCnpj() string {
	if m != nil {
		return m.Cnpj
	}
	return ""
}

type ExpedidorRequest struct {
	Endereco             *Endereco `protobuf:"bytes,1,opt,name=endereco,proto3" json:"endereco,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ExpedidorRequest) Reset()         { *m = ExpedidorRequest{} }
func (m *ExpedidorRequest) String() string { return proto.CompactTextString(m) }
func (*ExpedidorRequest) ProtoMessage()    {}
func (*ExpedidorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{3}
}

func (m *ExpedidorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpedidorRequest.Unmarshal(m, b)
}
func (m *ExpedidorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpedidorRequest.Marshal(b, m, deterministic)
}
func (m *ExpedidorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpedidorRequest.Merge(m, src)
}
func (m *ExpedidorRequest) XXX_Size() int {
	return xxx_messageInfo_ExpedidorRequest.Size(m)
}
func (m *ExpedidorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpedidorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExpedidorRequest proto.InternalMessageInfo

func (m *ExpedidorRequest) GetEndereco() *Endereco {
	if m != nil {
		return m.Endereco
	}
	return nil
}

type DestinatarioRequest struct {
	TipoPessoa           DestinatarioRequest_TipoPessoa `protobuf:"varint,1,opt,name=tipo_pessoa,json=tipoPessoa,proto3,enum=freterapido.DestinatarioRequest_TipoPessoa" json:"tipo_pessoa,omitempty"`
	CnpjCpf              string                         `protobuf:"bytes,2,opt,name=cnpj_cpf,json=cnpjCpf,proto3" json:"cnpj_cpf,omitempty"`
	InscricaoEstadual    string                         `protobuf:"bytes,3,opt,name=inscricao_estadual,json=inscricaoEstadual,proto3" json:"inscricao_estadual,omitempty"`
	Endereco             *Endereco                      `protobuf:"bytes,4,opt,name=endereco,proto3" json:"endereco,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *DestinatarioRequest) Reset()         { *m = DestinatarioRequest{} }
func (m *DestinatarioRequest) String() string { return proto.CompactTextString(m) }
func (*DestinatarioRequest) ProtoMessage()    {}
func (*DestinatarioRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{4}
}

func (m *DestinatarioRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestinatarioRequest.Unmarshal(m, b)
}
func (m *DestinatarioRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestinatarioRequest.Marshal(b, m, deterministic)
}
func (m *DestinatarioRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestinatarioRequest.Merge(m, src)
}
func (m *DestinatarioRequest) XXX_Size() int {
	return xxx_messageInfo_DestinatarioRequest.Size(m)
}
func (m *DestinatarioRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DestinatarioRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DestinatarioRequest proto.InternalMessageInfo

func (m *DestinatarioRequest) GetTipoPessoa() DestinatarioRequest_TipoPessoa {
	if m != nil {
		return m.TipoPessoa
	}
	return DestinatarioRequest_TIPOPESSOA_UNKNOWN
}

func (m *DestinatarioRequest) GetCnpjCpf() string {
	if m != nil {
		return m.CnpjCpf
	}
	return ""
}

func (m *DestinatarioRequest) GetInscricaoEstadual() string {
	if m != nil {
		return m.InscricaoEstadual
	}
	return ""
}

func (m *DestinatarioRequest) GetEndereco() *Endereco {
	if m != nil {
		return m.Endereco
	}
	return nil
}

type VolumeRequest struct {
	Tipo                 int32                 `protobuf:"varint,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Sku                  *wrappers.StringValue `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Descricao            *wrappers.StringValue `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
	Quantidade           int32                 `protobuf:"varint,4,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
	Altura               float64               `protobuf:"fixed64,5,opt,name=altura,proto3" json:"altura,omitempty"`
	Largura              float64               `protobuf:"fixed64,6,opt,name=largura,proto3" json:"largura,omitempty"`
	Comprimento          float64               `protobuf:"fixed64,7,opt,name=comprimento,proto3" json:"comprimento,omitempty"`
	Peso                 float64               `protobuf:"fixed64,8,opt,name=peso,proto3" json:"peso,omitempty"`
	Valor                float64               `protobuf:"fixed64,9,opt,name=valor,proto3" json:"valor,omitempty"`
	VolumesProduto       int32                 `protobuf:"varint,10,opt,name=volumes_produto,json=volumesProduto,proto3" json:"volumes_produto,omitempty"`
	Consolidar           bool                  `protobuf:"varint,11,opt,name=consolidar,proto3" json:"consolidar,omitempty"`
	Sobreposto           bool                  `protobuf:"varint,12,opt,name=sobreposto,proto3" json:"sobreposto,omitempty"`
	Tombar               bool                  `protobuf:"varint,13,opt,name=tombar,proto3" json:"tombar,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VolumeRequest) Reset()         { *m = VolumeRequest{} }
func (m *VolumeRequest) String() string { return proto.CompactTextString(m) }
func (*VolumeRequest) ProtoMessage()    {}
func (*VolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{5}
}

func (m *VolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeRequest.Unmarshal(m, b)
}
func (m *VolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeRequest.Marshal(b, m, deterministic)
}
func (m *VolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeRequest.Merge(m, src)
}
func (m *VolumeRequest) XXX_Size() int {
	return xxx_messageInfo_VolumeRequest.Size(m)
}
func (m *VolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeRequest proto.InternalMessageInfo

func (m *VolumeRequest) GetTipo() int32 {
	if m != nil {
		return m.Tipo
	}
	return 0
}

func (m *VolumeRequest) GetSku() *wrappers.StringValue {
	if m != nil {
		return m.Sku
	}
	return nil
}

func (m *VolumeRequest) GetDescricao() *wrappers.StringValue {
	if m != nil {
		return m.Descricao
	}
	return nil
}

func (m *VolumeRequest) GetQuantidade() int32 {
	if m != nil {
		return m.Quantidade
	}
	return 0
}

func (m *VolumeRequest) GetAltura() float64 {
	if m != nil {
		return m.Altura
	}
	return 0
}

func (m *VolumeRequest) GetLargura() float64 {
	if m != nil {
		return m.Largura
	}
	return 0
}

func (m *VolumeRequest) GetComprimento() float64 {
	if m != nil {
		return m.Comprimento
	}
	return 0
}

func (m *VolumeRequest) GetPeso() float64 {
	if m != nil {
		return m.Peso
	}
	return 0
}

func (m *VolumeRequest) GetValor() float64 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *VolumeRequest) GetVolumesProduto() int32 {
	if m != nil {
		return m.VolumesProduto
	}
	return 0
}

func (m *VolumeRequest) GetConsolidar() bool {
	if m != nil {
		return m.Consolidar
	}
	return false
}

func (m *VolumeRequest) GetSobreposto() bool {
	if m != nil {
		return m.Sobreposto
	}
	return false
}

func (m *VolumeRequest) GetTombar() bool {
	if m != nil {
		return m.Tombar
	}
	return false
}

type CalcularFreteResponse struct {
	TokenOferta          string                    `protobuf:"bytes,1,opt,name=token_oferta,json=tokenOferta,proto3" json:"token_oferta,omitempty"`
	Transportadoras      []*TransportadoraResponse `protobuf:"bytes,2,rep,name=transportadoras,proto3" json:"transportadoras,omitempty"`
	Volumes              []*VolumeResponse         `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CalcularFreteResponse) Reset()         { *m = CalcularFreteResponse{} }
func (m *CalcularFreteResponse) String() string { return proto.CompactTextString(m) }
func (*CalcularFreteResponse) ProtoMessage()    {}
func (*CalcularFreteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{6}
}

func (m *CalcularFreteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalcularFreteResponse.Unmarshal(m, b)
}
func (m *CalcularFreteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalcularFreteResponse.Marshal(b, m, deterministic)
}
func (m *CalcularFreteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalcularFreteResponse.Merge(m, src)
}
func (m *CalcularFreteResponse) XXX_Size() int {
	return xxx_messageInfo_CalcularFreteResponse.Size(m)
}
func (m *CalcularFreteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalcularFreteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalcularFreteResponse proto.InternalMessageInfo

func (m *CalcularFreteResponse) GetTokenOferta() string {
	if m != nil {
		return m.TokenOferta
	}
	return ""
}

func (m *CalcularFreteResponse) GetTransportadoras() []*TransportadoraResponse {
	if m != nil {
		return m.Transportadoras
	}
	return nil
}

func (m *CalcularFreteResponse) GetVolumes() []*VolumeResponse {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type TransportadoraResponse struct {
	Oferta               int64                 `protobuf:"varint,1,opt,name=oferta,proto3" json:"oferta,omitempty"`
	Cnpj                 string                `protobuf:"bytes,2,opt,name=cnpj,proto3" json:"cnpj,omitempty"`
	Logotipo             string                `protobuf:"bytes,3,opt,name=logotipo,proto3" json:"logotipo,omitempty"`
	Nome                 string                `protobuf:"bytes,4,opt,name=nome,proto3" json:"nome,omitempty"`
	Servico              string                `protobuf:"bytes,5,opt,name=servico,proto3" json:"servico,omitempty"`
	DescricaoServico     *wrappers.StringValue `protobuf:"bytes,6,opt,name=descricao_servico,json=descricaoServico,proto3" json:"descricao_servico,omitempty"`
	PrazoEntrega         int32                 `protobuf:"varint,7,opt,name=prazo_entrega,json=prazoEntrega,proto3" json:"prazo_entrega,omitempty"`
	Validade             *timestamp.Timestamp  `protobuf:"bytes,8,opt,name=validade,proto3" json:"validade,omitempty"`
	CustoFrete           float64               `protobuf:"fixed64,9,opt,name=custo_frete,json=custoFrete,proto3" json:"custo_frete,omitempty"`
	PrecoFrete           float64               `protobuf:"fixed64,10,opt,name=preco_frete,json=precoFrete,proto3" json:"preco_frete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TransportadoraResponse) Reset()         { *m = TransportadoraResponse{} }
func (m *TransportadoraResponse) String() string { return proto.CompactTextString(m) }
func (*TransportadoraResponse) ProtoMessage()    {}
func (*TransportadoraResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{7}
}

func (m *TransportadoraResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportadoraResponse.Unmarshal(m, b)
}
func (m *TransportadoraResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportadoraResponse.Marshal(b, m, deterministic)
}
func (m *TransportadoraResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportadoraResponse.Merge(m, src)
}
func (m *TransportadoraResponse) XXX_Size() int {
	return xxx_messageInfo_TransportadoraResponse.Size(m)
}
func (m *TransportadoraResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportadoraResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransportadoraResponse proto.InternalMessageInfo

func (m *TransportadoraResponse) GetOferta() int64 {
	if m != nil {
		return m.Oferta
	}
	return 0
}

func (m *TransportadoraResponse) GetCnpj() string {
	if m != nil {
		return m.Cnpj
	}
	return ""
}

func (m *TransportadoraResponse) GetLogotipo() string {
	if m != nil {
		return m.Logotipo
	}
	return ""
}

func (m *TransportadoraResponse) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *TransportadoraResponse) GetServico() string {
	if m != nil {
		return m.Servico
	}
	return ""
}

func (m *TransportadoraResponse) GetDescricaoServico() *wrappers.StringValue {
	if m != nil {
		return m.DescricaoServico
	}
	return nil
}

func (m *TransportadoraResponse) GetPrazoEntrega() int32 {
	if m != nil {
		return m.PrazoEntrega
	}
	return 0
}

func (m *TransportadoraResponse) GetValidade() *timestamp.Timestamp {
	if m != nil {
		return m.Validade
	}
	return nil
}

func (m *TransportadoraResponse) GetCustoFrete() float64 {
	if m != nil {
		return m.CustoFrete
	}
	return 0
}

func (m *TransportadoraResponse) GetPrecoFrete() float64 {
	if m != nil {
		return m.PrecoFrete
	}
	return 0
}

type VolumeResponse struct {
	Tipo                 int32                 `protobuf:"varint,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Sku                  *wrappers.StringValue `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Descricao            *wrappers.StringValue `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
	Quantidade           int32                 `protobuf:"varint,4,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
	Altura               float64               `protobuf:"fixed64,5,opt,name=altura,proto3" json:"altura,omitempty"`
	Largura              float64               `protobuf:"fixed64,6,opt,name=largura,proto3" json:"largura,omitempty"`
	Comprimento          float64               `protobuf:"fixed64,7,opt,name=comprimento,proto3" json:"comprimento,omitempty"`
	Peso                 float64               `protobuf:"fixed64,8,opt,name=peso,proto3" json:"peso,omitempty"`
	Valor                float64               `protobuf:"fixed64,9,opt,name=valor,proto3" json:"valor,omitempty"`
	VolumesProduto       int32                 `protobuf:"varint,10,opt,name=volumes_produto,json=volumesProduto,proto3" json:"volumes_produto,omitempty"`
	Items                []*VolumeResponse     `protobuf:"bytes,11,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *VolumeResponse) Reset()         { *m = VolumeResponse{} }
func (m *VolumeResponse) String() string { return proto.CompactTextString(m) }
func (*VolumeResponse) ProtoMessage()    {}
func (*VolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_879dc8970752a9f2, []int{8}
}

func (m *VolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeResponse.Unmarshal(m, b)
}
func (m *VolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeResponse.Marshal(b, m, deterministic)
}
func (m *VolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeResponse.Merge(m, src)
}
func (m *VolumeResponse) XXX_Size() int {
	return xxx_messageInfo_VolumeResponse.Size(m)
}
func (m *VolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeResponse proto.InternalMessageInfo

func (m *VolumeResponse) GetTipo() int32 {
	if m != nil {
		return m.Tipo
	}
	return 0
}

func (m *VolumeResponse) GetSku() *wrappers.StringValue {
	if m != nil {
		return m.Sku
	}
	return nil
}

func (m *VolumeResponse) GetDescricao() *wrappers.StringValue {
	if m != nil {
		return m.Descricao
	}
	return nil
}

func (m *VolumeResponse) GetQuantidade() int32 {
	if m != nil {
		return m.Quantidade
	}
	return 0
}

func (m *VolumeResponse) GetAltura() float64 {
	if m != nil {
		return m.Altura
	}
	return 0
}

func (m *VolumeResponse) GetLargura() float64 {
	if m != nil {
		return m.Largura
	}
	return 0
}

func (m *VolumeResponse) GetComprimento() float64 {
	if m != nil {
		return m.Comprimento
	}
	return 0
}

func (m *VolumeResponse) GetPeso() float64 {
	if m != nil {
		return m.Peso
	}
	return 0
}

func (m *VolumeResponse) GetValor() float64 {
	if m != nil {
		return m.Valor
	}
	return 0
}

func (m *VolumeResponse) GetVolumesProduto() int32 {
	if m != nil {
		return m.VolumesProduto
	}
	return 0
}

func (m *VolumeResponse) GetItems() []*VolumeResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterEnum("freterapido.CalcularFreteRequest_TipoCobranca", CalcularFreteRequest_TipoCobranca_name, CalcularFreteRequest_TipoCobranca_value)
	proto.RegisterEnum("freterapido.CalcularFreteRequest_Filtro", CalcularFreteRequest_Filtro_name, CalcularFreteRequest_Filtro_value)
	proto.RegisterEnum("freterapido.DestinatarioRequest_TipoPessoa", DestinatarioRequest_TipoPessoa_name, DestinatarioRequest_TipoPessoa_value)
	proto.RegisterType((*CalcularFreteRequest)(nil), "freterapido.CalcularFreteRequest")
	proto.RegisterType((*Endereco)(nil), "freterapido.Endereco")
	proto.RegisterType((*RemetenteRequest)(nil), "freterapido.RemetenteRequest")
	proto.RegisterType((*ExpedidorRequest)(nil), "freterapido.ExpedidorRequest")
	proto.RegisterType((*DestinatarioRequest)(nil), "freterapido.DestinatarioRequest")
	proto.RegisterType((*VolumeRequest)(nil), "freterapido.VolumeRequest")
	proto.RegisterType((*CalcularFreteResponse)(nil), "freterapido.CalcularFreteResponse")
	proto.RegisterType((*TransportadoraResponse)(nil), "freterapido.TransportadoraResponse")
	proto.RegisterType((*VolumeResponse)(nil), "freterapido.VolumeResponse")
}

func init() { proto.RegisterFile("freterapido.proto", fileDescriptor_879dc8970752a9f2) }

var fileDescriptor_879dc8970752a9f2 = []byte{
	// 1101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0x41, 0x6f, 0xdb, 0x46,
	0x13, 0x0d, 0xa5, 0x48, 0x96, 0x86, 0x72, 0x42, 0x6d, 0x6c, 0x7f, 0xfc, 0x94, 0x34, 0x51, 0x14,
	0xa0, 0x15, 0x10, 0x54, 0x41, 0xe4, 0x34, 0x87, 0xf6, 0x52, 0x47, 0x96, 0x00, 0xb5, 0xb1, 0x25,
	0xac, 0x14, 0x17, 0xe8, 0x85, 0x58, 0x93, 0x2b, 0x81, 0x0d, 0xc5, 0x65, 0x96, 0x4b, 0xb7, 0xe8,
	0x4f, 0xe8, 0x8f, 0xe9, 0xb1, 0xe7, 0xfe, 0xab, 0xf6, 0x58, 0xec, 0x72, 0x49, 0x91, 0xb6, 0x10,
	0xe7, 0xd0, 0x63, 0x6f, 0xbb, 0xef, 0xbd, 0x59, 0xee, 0x70, 0x66, 0x1e, 0x09, 0xed, 0x15, 0xa7,
	0x82, 0x72, 0x12, 0xf9, 0x1e, 0x1b, 0x44, 0x9c, 0x09, 0x86, 0xcc, 0x02, 0xd4, 0x79, 0xbc, 0x66,
	0x6c, 0x1d, 0xd0, 0x17, 0x8a, 0xba, 0x4c, 0x56, 0x2f, 0x7e, 0xe6, 0x24, 0x8a, 0x28, 0x8f, 0x53,
	0x71, 0xe7, 0xc9, 0x75, 0x5e, 0xf8, 0x1b, 0x1a, 0x0b, 0xb2, 0x89, 0x52, 0x41, 0xef, 0xaf, 0x1a,
	0x1c, 0x8c, 0x48, 0xe0, 0x26, 0x01, 0xe1, 0x13, 0x79, 0x30, 0xa6, 0x1f, 0x12, 0x1a, 0x0b, 0xb4,
	0x80, 0x7d, 0xe1, 0x47, 0xcc, 0x71, 0xd9, 0x25, 0x27, 0xa1, 0x4b, 0x6c, 0xa3, 0x6b, 0xf4, 0xef,
	0x0d, 0x07, 0x83, 0xe2, 0x8d, 0x76, 0x45, 0x0e, 0x96, 0x7e, 0xc4, 0x46, 0x3a, 0x0a, 0xb7, 0x44,
	0x61, 0x87, 0xbe, 0x85, 0xfa, 0xca, 0x0f, 0x04, 0x67, 0x76, 0x45, 0x9d, 0xd6, 0xbf, 0xfd, 0xb4,
	0x89, 0xd2, 0x63, 0x1d, 0x87, 0x8e, 0xa1, 0x1e, 0xf8, 0x1b, 0x5f, 0x50, 0xbb, 0xda, 0x35, 0xfa,
	0xe6, 0xf0, 0xe1, 0x20, 0xcd, 0x70, 0x90, 0x65, 0x38, 0x98, 0x86, 0xe2, 0xf5, 0xab, 0x0b, 0x12,
	0x24, 0x14, 0x6b, 0x29, 0x3a, 0x80, 0x9a, 0x60, 0xef, 0x69, 0x68, 0xdf, 0xed, 0x1a, 0xfd, 0x26,
	0x4e, 0x37, 0xe8, 0x39, 0xb4, 0x5d, 0xe6, 0xf9, 0x6b, 0xe6, 0x44, 0x01, 0x11, 0x64, 0xc5, 0xf8,
	0x86, 0xd8, 0x35, 0xa5, 0xb0, 0x52, 0x62, 0x9e, 0xe3, 0xe8, 0x18, 0x0e, 0x39, 0x15, 0x8c, 0x87,
	0x84, 0x3b, 0x2e, 0x0b, 0x63, 0x16, 0xf8, 0x1e, 0x71, 0x09, 0xb3, 0xeb, 0x5d, 0xa3, 0xdf, 0xc0,
	0x07, 0x19, 0x39, 0x2a, 0x70, 0xe8, 0x1b, 0x68, 0x72, 0xba, 0xa1, 0x82, 0x86, 0x82, 0xda, 0x7b,
	0xea, 0xbe, 0x9f, 0x95, 0x32, 0xc6, 0x19, 0xab, 0xb3, 0xc5, 0x5b, 0xbd, 0x0c, 0xa6, 0xbf, 0x44,
	0xd4, 0xf3, 0x3d, 0xc6, 0xed, 0xc6, 0x8e, 0xe0, 0x71, 0xc6, 0xe6, 0xc1, 0xb9, 0x1e, 0x9d, 0x42,
	0xcb, 0xa3, 0xb1, 0xf0, 0x43, 0x22, 0x08, 0xf7, 0x99, 0xdd, 0x54, 0xf1, 0xdd, 0x52, 0xfc, 0x69,
	0x41, 0x90, 0x1d, 0x51, 0x8a, 0x42, 0xaf, 0x60, 0xef, 0x8a, 0x05, 0xc9, 0x86, 0xc6, 0x36, 0x74,
	0xab, 0x7d, 0x73, 0xd8, 0x29, 0x1d, 0x70, 0xa1, 0xb8, 0x2c, 0x34, 0x93, 0xf6, 0x96, 0xd0, 0x2a,
	0xb6, 0x00, 0xb2, 0xe1, 0x60, 0x39, 0x9d, 0xcf, 0x46, 0xb3, 0x37, 0xf8, 0xe4, 0x7c, 0x74, 0xe2,
	0xbc, 0x3b, 0xff, 0xfe, 0x7c, 0xf6, 0xc3, 0xb9, 0x75, 0x07, 0x1d, 0x80, 0x55, 0x62, 0x46, 0xd3,
	0x89, 0x65, 0xdc, 0x40, 0x27, 0xb3, 0x37, 0x56, 0xa5, 0x37, 0x83, 0x7a, 0xda, 0x0a, 0xe8, 0x10,
	0xda, 0x93, 0xe9, 0xdb, 0x25, 0x9e, 0x39, 0x8b, 0xf1, 0x99, 0x93, 0x2e, 0xad, 0x3b, 0xe8, 0x08,
	0x90, 0x86, 0xcf, 0xc6, 0xe7, 0x33, 0xec, 0xcc, 0xf1, 0x78, 0x34, 0xb3, 0x8c, 0x1d, 0xf8, 0xc9,
	0x8f, 0x33, 0xab, 0xd2, 0x7b, 0x04, 0x8d, 0x71, 0xe8, 0x51, 0x4e, 0x5d, 0x86, 0x2c, 0xa8, 0xba,
	0x34, 0x52, 0x2d, 0xde, 0xc4, 0x72, 0xd9, 0xfb, 0x1c, 0xac, 0xeb, 0xc5, 0x41, 0x08, 0xee, 0xba,
	0x61, 0xf4, 0x93, 0x96, 0xa9, 0x75, 0x6f, 0x0c, 0xd6, 0xf5, 0x3a, 0xa0, 0x97, 0xd0, 0xa0, 0xfa,
	0x64, 0xa5, 0x35, 0x87, 0x87, 0xe5, 0xc2, 0x69, 0x12, 0xe7, 0xb2, 0xde, 0x1f, 0x15, 0x78, 0xb0,
	0xa3, 0x1e, 0xe8, 0x2d, 0x98, 0x6a, 0x0a, 0x23, 0x1a, 0xc7, 0x2c, 0x9b, 0xc1, 0xe7, 0xb7, 0x95,
	0x51, 0x8d, 0xe0, 0x5c, 0x85, 0x60, 0x10, 0xf9, 0x1a, 0xfd, 0x1f, 0x1a, 0xf2, 0xd2, 0x8e, 0x1b,
	0xad, 0xd4, 0x00, 0x36, 0xf1, 0x9e, 0xdc, 0x8f, 0xa2, 0x15, 0xfa, 0x12, 0x90, 0x1f, 0xc6, 0x2e,
	0xf7, 0x5d, 0xc2, 0x1c, 0xe9, 0x10, 0x5e, 0x42, 0x02, 0x35, 0x63, 0x4d, 0xdc, 0xce, 0x99, 0xb1,
	0x26, 0x4a, 0x29, 0xde, 0xfd, 0xb4, 0x14, 0x97, 0x00, 0xdb, 0x6b, 0xc9, 0xaa, 0xc8, 0x22, 0xcf,
	0xc7, 0x8b, 0xc5, 0xac, 0xd8, 0x12, 0x87, 0xd0, 0x2e, 0xe0, 0x93, 0xe9, 0x62, 0x3a, 0x3a, 0xb1,
	0x0c, 0xf4, 0x3f, 0x78, 0x50, 0x80, 0xbf, 0x7b, 0x87, 0xa7, 0xa7, 0x92, 0xa8, 0xf4, 0x7e, 0xaf,
	0xc2, 0x7e, 0xa9, 0x0f, 0x65, 0x95, 0x64, 0xca, 0xea, 0x5d, 0xd5, 0xb0, 0x5a, 0xa3, 0x01, 0x54,
	0xe3, 0xf7, 0x89, 0xca, 0xd9, 0x1c, 0x3e, 0xba, 0x61, 0x19, 0x0b, 0xc1, 0xfd, 0x70, 0x9d, 0x7a,
	0x86, 0x14, 0xa2, 0xaf, 0xa1, 0xe9, 0x51, 0x9d, 0xb3, 0x36, 0x9a, 0x8f, 0x47, 0x6d, 0xe5, 0xe8,
	0x31, 0xc0, 0x87, 0x84, 0x84, 0xc2, 0xf7, 0x88, 0x47, 0xd5, 0xcb, 0xa9, 0xe1, 0x02, 0x82, 0x8e,
	0xa0, 0x4e, 0x02, 0x91, 0xf0, 0xd4, 0x6b, 0x0c, 0xac, 0x77, 0xc8, 0x86, 0xbd, 0x80, 0xf0, 0xb5,
	0x24, 0xea, 0x8a, 0xc8, 0xb6, 0xa8, 0x0b, 0xa6, 0xcb, 0x36, 0x11, 0xf7, 0x37, 0x34, 0x14, 0x4c,
	0x19, 0x89, 0x81, 0x8b, 0x90, 0xcc, 0x39, 0xa2, 0x31, 0x53, 0x36, 0x61, 0x60, 0xb5, 0x96, 0xa6,
	0x77, 0x45, 0x02, 0xc6, 0xd5, 0xec, 0x1b, 0x38, 0xdd, 0xa0, 0x2f, 0xe0, 0xbe, 0x9e, 0x53, 0x27,
	0xe2, 0xcc, 0x4b, 0x04, 0xb3, 0x41, 0x5d, 0xf1, 0x9e, 0x86, 0xe7, 0x29, 0x2a, 0xd3, 0xc8, 0x7d,
	0x8e, 0xdb, 0xa6, 0x72, 0xb9, 0x02, 0x22, 0xf9, 0x98, 0x5d, 0x72, 0x1a, 0xb1, 0x58, 0x30, 0xbb,
	0x95, 0xf2, 0x5b, 0x44, 0xa6, 0x29, 0xd8, 0xe6, 0x92, 0x70, 0x7b, 0x5f, 0x71, 0x7a, 0xd7, 0xfb,
	0xd3, 0x80, 0xc3, 0x6b, 0x46, 0x1f, 0x47, 0x2c, 0x8c, 0x29, 0x7a, 0x0a, 0x2d, 0x65, 0xcc, 0x0e,
	0x5b, 0x51, 0x2e, 0x88, 0x1e, 0x33, 0x53, 0x61, 0x33, 0x05, 0xa1, 0x33, 0xb8, 0x2f, 0x38, 0x09,
	0xe3, 0x88, 0x71, 0x41, 0x3c, 0xc6, 0x49, 0x6c, 0x57, 0x94, 0x31, 0x3d, 0x2b, 0x75, 0xdf, 0xb2,
	0xa4, 0xc9, 0x1e, 0x80, 0xaf, 0xc7, 0xa2, 0xaf, 0xb6, 0xfe, 0x56, 0x55, 0xc7, 0x3c, 0xdc, 0xe9,
	0x6f, 0x3a, 0x3c, 0x37, 0xb8, 0xbf, 0x2b, 0x70, 0xb4, 0xfb, 0x11, 0x32, 0xeb, 0xc2, 0xed, 0xab,
	0x58, 0xef, 0x72, 0xeb, 0xa8, 0x6c, 0xad, 0x03, 0x75, 0xa0, 0x11, 0xb0, 0x35, 0x53, 0xcd, 0x9a,
	0x0e, 0x5a, 0xbe, 0x97, 0xfa, 0x90, 0x6d, 0xa8, 0xfe, 0x60, 0xa9, 0xb5, 0x6c, 0x90, 0x98, 0xf2,
	0x2b, 0xdf, 0x65, 0xfa, 0x2b, 0x95, 0x6d, 0xd1, 0x14, 0xda, 0x79, 0xff, 0x39, 0x99, 0xa6, 0xfe,
	0x09, 0x6d, 0x6b, 0xe5, 0x61, 0x0b, 0x7d, 0xd4, 0x33, 0xd8, 0x8f, 0x38, 0xf9, 0x95, 0x39, 0x34,
	0x14, 0x9c, 0xae, 0x89, 0xea, 0xb6, 0x1a, 0x6e, 0x29, 0x70, 0x9c, 0x62, 0xe8, 0x35, 0x34, 0xae,
	0x48, 0x90, 0x36, 0x78, 0xfa, 0x65, 0xea, 0xdc, 0x78, 0xcc, 0x32, 0xfb, 0xd1, 0xc0, 0xb9, 0x16,
	0x3d, 0x01, 0xd3, 0x4d, 0x62, 0xc1, 0x1c, 0xf5, 0x96, 0x75, 0x63, 0x82, 0x82, 0x54, 0x2b, 0x48,
	0x41, 0x24, 0xcd, 0x42, 0x0b, 0x20, 0x15, 0x28, 0x48, 0x09, 0x7a, 0xbf, 0x55, 0xe1, 0x5e, 0xb9,
	0x2c, 0xff, 0xcd, 0xfb, 0xbf, 0x33, 0xef, 0x2f, 0xa1, 0xe6, 0x0b, 0xba, 0x89, 0x6d, 0xf3, 0xf6,
	0x49, 0x48, 0x95, 0x43, 0x0a, 0x66, 0x3a, 0xc1, 0x4a, 0x84, 0x2e, 0x60, 0xbf, 0x34, 0xd8, 0xe8,
	0xe9, 0xad, 0x7f, 0x77, 0x9d, 0xde, 0xc7, 0x24, 0xe9, 0xd3, 0x2e, 0xeb, 0xaa, 0x02, 0xc7, 0xff,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x99, 0x25, 0xe2, 0x3c, 0x0c, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FreteRapidoClient is the client API for FreteRapido service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FreteRapidoClient interface {
	CalcularFrete(ctx context.Context, in *CalcularFreteRequest, opts ...grpc.CallOption) (*CalcularFreteResponse, error)
}

type freteRapidoClient struct {
	cc *grpc.ClientConn
}

func NewFreteRapidoClient(cc *grpc.ClientConn) FreteRapidoClient {
	return &freteRapidoClient{cc}
}

func (c *freteRapidoClient) CalcularFrete(ctx context.Context, in *CalcularFreteRequest, opts ...grpc.CallOption) (*CalcularFreteResponse, error) {
	out := new(CalcularFreteResponse)
	err := c.cc.Invoke(ctx, "/freterapido.FreteRapido/CalcularFrete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FreteRapidoServer is the server API for FreteRapido service.
type FreteRapidoServer interface {
	CalcularFrete(context.Context, *CalcularFreteRequest) (*CalcularFreteResponse, error)
}

func RegisterFreteRapidoServer(s *grpc.Server, srv FreteRapidoServer) {
	s.RegisterService(&_FreteRapido_serviceDesc, srv)
}

func _FreteRapido_CalcularFrete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcularFreteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreteRapidoServer).CalcularFrete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/freterapido.FreteRapido/CalcularFrete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreteRapidoServer).CalcularFrete(ctx, req.(*CalcularFreteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FreteRapido_serviceDesc = grpc.ServiceDesc{
	ServiceName: "freterapido.FreteRapido",
	HandlerType: (*FreteRapidoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalcularFrete",
			Handler:    _FreteRapido_CalcularFrete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "freterapido.proto",
}
