<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido;

if (false) {
    /**
     * This class is deprecated. Use Freterapido\CalcularFreteRequest\Filtro instead.
     * @deprecated
     */
    class CalcularFreteRequest_Filtro {}
}
class_exists(CalcularFreteRequest\Filtro::class);
@trigger_error('Freterapido\CalcularFreteRequest_Filtro is deprecated and will be removed in the next major release. Use Freterapido\CalcularFreteRequest\Filtro instead', E_USER_DEPRECATED);

