<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>freterapido.CalcularFreteRequest</code>
 */
class CalcularFreteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.freterapido.CalcularFreteRequest.TipoCobranca tipo_cobranca = 1;</code>
     */
    private $tipo_cobranca = 0;
    /**
     * Generated from protobuf field <code>.freterapido.CalcularFreteRequest.Filtro filtro = 2;</code>
     */
    private $filtro = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Int64Value limite = 3;</code>
     */
    private $limite = null;
    /**
     * Generated from protobuf field <code>string token = 4;</code>
     */
    private $token = '';
    /**
     * Generated from protobuf field <code>string codigo_plataforma = 5;</code>
     */
    private $codigo_plataforma = '';
    /**
     * Generated from protobuf field <code>bool retornar_consolidacao = 6;</code>
     */
    private $retornar_consolidacao = false;
    /**
     * Generated from protobuf field <code>.freterapido.RemetenteRequest remetente = 7;</code>
     */
    private $remetente = null;
    /**
     * Generated from protobuf field <code>.freterapido.ExpedidorRequest expedidor = 8;</code>
     */
    private $expedidor = null;
    /**
     * Generated from protobuf field <code>.freterapido.DestinatarioRequest destinatario = 9;</code>
     */
    private $destinatario = null;
    /**
     * Generated from protobuf field <code>repeated .freterapido.VolumeRequest volumes = 10;</code>
     */
    private $volumes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $tipo_cobranca
     *     @type int $filtro
     *     @type \Google\Protobuf\Int64Value $limite
     *     @type string $token
     *     @type string $codigo_plataforma
     *     @type bool $retornar_consolidacao
     *     @type \Freterapido\RemetenteRequest $remetente
     *     @type \Freterapido\ExpedidorRequest $expedidor
     *     @type \Freterapido\DestinatarioRequest $destinatario
     *     @type \Freterapido\VolumeRequest[]|\Google\Protobuf\Internal\RepeatedField $volumes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Freterapido::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.freterapido.CalcularFreteRequest.TipoCobranca tipo_cobranca = 1;</code>
     * @return int
     */
    public function getTipoCobranca()
    {
        return $this->tipo_cobranca;
    }

    /**
     * Generated from protobuf field <code>.freterapido.CalcularFreteRequest.TipoCobranca tipo_cobranca = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTipoCobranca($var)
    {
        GPBUtil::checkEnum($var, \Freterapido\CalcularFreteRequest_TipoCobranca::class);
        $this->tipo_cobranca = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.freterapido.CalcularFreteRequest.Filtro filtro = 2;</code>
     * @return int
     */
    public function getFiltro()
    {
        return $this->filtro;
    }

    /**
     * Generated from protobuf field <code>.freterapido.CalcularFreteRequest.Filtro filtro = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFiltro($var)
    {
        GPBUtil::checkEnum($var, \Freterapido\CalcularFreteRequest_Filtro::class);
        $this->filtro = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int64Value limite = 3;</code>
     * @return \Google\Protobuf\Int64Value
     */
    public function getLimite()
    {
        return $this->limite;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int64Value limite = 3;</code>
     * @param \Google\Protobuf\Int64Value $var
     * @return $this
     */
    public function setLimite($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int64Value::class);
        $this->limite = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token = 4;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string codigo_plataforma = 5;</code>
     * @return string
     */
    public function getCodigoPlataforma()
    {
        return $this->codigo_plataforma;
    }

    /**
     * Generated from protobuf field <code>string codigo_plataforma = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCodigoPlataforma($var)
    {
        GPBUtil::checkString($var, True);
        $this->codigo_plataforma = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool retornar_consolidacao = 6;</code>
     * @return bool
     */
    public function getRetornarConsolidacao()
    {
        return $this->retornar_consolidacao;
    }

    /**
     * Generated from protobuf field <code>bool retornar_consolidacao = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setRetornarConsolidacao($var)
    {
        GPBUtil::checkBool($var);
        $this->retornar_consolidacao = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.freterapido.RemetenteRequest remetente = 7;</code>
     * @return \Freterapido\RemetenteRequest
     */
    public function getRemetente()
    {
        return $this->remetente;
    }

    /**
     * Generated from protobuf field <code>.freterapido.RemetenteRequest remetente = 7;</code>
     * @param \Freterapido\RemetenteRequest $var
     * @return $this
     */
    public function setRemetente($var)
    {
        GPBUtil::checkMessage($var, \Freterapido\RemetenteRequest::class);
        $this->remetente = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.freterapido.ExpedidorRequest expedidor = 8;</code>
     * @return \Freterapido\ExpedidorRequest
     */
    public function getExpedidor()
    {
        return $this->expedidor;
    }

    /**
     * Generated from protobuf field <code>.freterapido.ExpedidorRequest expedidor = 8;</code>
     * @param \Freterapido\ExpedidorRequest $var
     * @return $this
     */
    public function setExpedidor($var)
    {
        GPBUtil::checkMessage($var, \Freterapido\ExpedidorRequest::class);
        $this->expedidor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.freterapido.DestinatarioRequest destinatario = 9;</code>
     * @return \Freterapido\DestinatarioRequest
     */
    public function getDestinatario()
    {
        return $this->destinatario;
    }

    /**
     * Generated from protobuf field <code>.freterapido.DestinatarioRequest destinatario = 9;</code>
     * @param \Freterapido\DestinatarioRequest $var
     * @return $this
     */
    public function setDestinatario($var)
    {
        GPBUtil::checkMessage($var, \Freterapido\DestinatarioRequest::class);
        $this->destinatario = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .freterapido.VolumeRequest volumes = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVolumes()
    {
        return $this->volumes;
    }

    /**
     * Generated from protobuf field <code>repeated .freterapido.VolumeRequest volumes = 10;</code>
     * @param \Freterapido\VolumeRequest[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVolumes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Freterapido\VolumeRequest::class);
        $this->volumes = $arr;

        return $this;
    }

}

