<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>freterapido.CalcularFreteResponse</code>
 */
class CalcularFreteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string token_oferta = 1;</code>
     */
    private $token_oferta = '';
    /**
     * Generated from protobuf field <code>repeated .freterapido.TransportadoraResponse transportadoras = 2;</code>
     */
    private $transportadoras;
    /**
     * Generated from protobuf field <code>repeated .freterapido.VolumeResponse volumes = 3;</code>
     */
    private $volumes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token_oferta
     *     @type \Freterapido\TransportadoraResponse[]|\Google\Protobuf\Internal\RepeatedField $transportadoras
     *     @type \Freterapido\VolumeResponse[]|\Google\Protobuf\Internal\RepeatedField $volumes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Freterapido::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string token_oferta = 1;</code>
     * @return string
     */
    public function getTokenOferta()
    {
        return $this->token_oferta;
    }

    /**
     * Generated from protobuf field <code>string token_oferta = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenOferta($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_oferta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .freterapido.TransportadoraResponse transportadoras = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransportadoras()
    {
        return $this->transportadoras;
    }

    /**
     * Generated from protobuf field <code>repeated .freterapido.TransportadoraResponse transportadoras = 2;</code>
     * @param \Freterapido\TransportadoraResponse[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransportadoras($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Freterapido\TransportadoraResponse::class);
        $this->transportadoras = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .freterapido.VolumeResponse volumes = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVolumes()
    {
        return $this->volumes;
    }

    /**
     * Generated from protobuf field <code>repeated .freterapido.VolumeResponse volumes = 3;</code>
     * @param \Freterapido\VolumeResponse[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVolumes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Freterapido\VolumeResponse::class);
        $this->volumes = $arr;

        return $this;
    }

}

