<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido;

if (false) {
    /**
     * This class is deprecated. Use Freterapido\CalcularFreteRequest\TipoCobranca instead.
     * @deprecated
     */
    class CalcularFreteRequest_TipoCobranca {}
}
class_exists(CalcularFreteRequest\TipoCobranca::class);
@trigger_error('Freterapido\CalcularFreteRequest_TipoCobranca is deprecated and will be removed in the next major release. Use Freterapido\CalcularFreteRequest\TipoCobranca instead', E_USER_DEPRECATED);

