<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>freterapido.DestinatarioRequest</code>
 */
class DestinatarioRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.freterapido.DestinatarioRequest.TipoPessoa tipo_pessoa = 1;</code>
     */
    private $tipo_pessoa = 0;
    /**
     * Generated from protobuf field <code>string cnpj_cpf = 2;</code>
     */
    private $cnpj_cpf = '';
    /**
     * Generated from protobuf field <code>string inscricao_estadual = 3;</code>
     */
    private $inscricao_estadual = '';
    /**
     * Generated from protobuf field <code>.freterapido.Endereco endereco = 4;</code>
     */
    private $endereco = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $tipo_pessoa
     *     @type string $cnpj_cpf
     *     @type string $inscricao_estadual
     *     @type \Freterapido\Endereco $endereco
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Freterapido::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.freterapido.DestinatarioRequest.TipoPessoa tipo_pessoa = 1;</code>
     * @return int
     */
    public function getTipoPessoa()
    {
        return $this->tipo_pessoa;
    }

    /**
     * Generated from protobuf field <code>.freterapido.DestinatarioRequest.TipoPessoa tipo_pessoa = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTipoPessoa($var)
    {
        GPBUtil::checkEnum($var, \Freterapido\DestinatarioRequest_TipoPessoa::class);
        $this->tipo_pessoa = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cnpj_cpf = 2;</code>
     * @return string
     */
    public function getCnpjCpf()
    {
        return $this->cnpj_cpf;
    }

    /**
     * Generated from protobuf field <code>string cnpj_cpf = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCnpjCpf($var)
    {
        GPBUtil::checkString($var, True);
        $this->cnpj_cpf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string inscricao_estadual = 3;</code>
     * @return string
     */
    public function getInscricaoEstadual()
    {
        return $this->inscricao_estadual;
    }

    /**
     * Generated from protobuf field <code>string inscricao_estadual = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setInscricaoEstadual($var)
    {
        GPBUtil::checkString($var, True);
        $this->inscricao_estadual = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.freterapido.Endereco endereco = 4;</code>
     * @return \Freterapido\Endereco
     */
    public function getEndereco()
    {
        return $this->endereco;
    }

    /**
     * Generated from protobuf field <code>.freterapido.Endereco endereco = 4;</code>
     * @param \Freterapido\Endereco $var
     * @return $this
     */
    public function setEndereco($var)
    {
        GPBUtil::checkMessage($var, \Freterapido\Endereco::class);
        $this->endereco = $var;

        return $this;
    }

}

