<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido;

if (false) {
    /**
     * This class is deprecated. Use Freterapido\DestinatarioRequest\TipoPessoa instead.
     * @deprecated
     */
    class DestinatarioRequest_TipoPessoa {}
}
class_exists(DestinatarioRequest\TipoPessoa::class);
@trigger_error('Freterapido\DestinatarioRequest_TipoPessoa is deprecated and will be removed in the next major release. Use Freterapido\DestinatarioRequest\TipoPessoa instead', E_USER_DEPRECATED);

