<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>freterapido.ExpedidorRequest</code>
 */
class ExpedidorRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.freterapido.Endereco endereco = 1;</code>
     */
    private $endereco = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Freterapido\Endereco $endereco
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Freterapido::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.freterapido.Endereco endereco = 1;</code>
     * @return \Freterapido\Endereco
     */
    public function getEndereco()
    {
        return $this->endereco;
    }

    /**
     * Generated from protobuf field <code>.freterapido.Endereco endereco = 1;</code>
     * @param \Freterapido\Endereco $var
     * @return $this
     */
    public function setEndereco($var)
    {
        GPBUtil::checkMessage($var, \Freterapido\Endereco::class);
        $this->endereco = $var;

        return $this;
    }

}

