<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>freterapido.RemetenteRequest</code>
 */
class RemetenteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string cnpj = 1;</code>
     */
    private $cnpj = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cnpj
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Freterapido::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cnpj = 1;</code>
     * @return string
     */
    public function getCnpj()
    {
        return $this->cnpj;
    }

    /**
     * Generated from protobuf field <code>string cnpj = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCnpj($var)
    {
        GPBUtil::checkString($var, True);
        $this->cnpj = $var;

        return $this;
    }

}

