<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: freterapido.proto

namespace Freterapido;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>freterapido.TransportadoraResponse</code>
 */
class TransportadoraResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 oferta = 1;</code>
     */
    private $oferta = 0;
    /**
     * Generated from protobuf field <code>string cnpj = 2;</code>
     */
    private $cnpj = '';
    /**
     * Generated from protobuf field <code>string logotipo = 3;</code>
     */
    private $logotipo = '';
    /**
     * Generated from protobuf field <code>string nome = 4;</code>
     */
    private $nome = '';
    /**
     * Generated from protobuf field <code>string servico = 5;</code>
     */
    private $servico = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue descricao_servico = 6;</code>
     */
    private $descricao_servico = null;
    /**
     * Generated from protobuf field <code>int32 prazo_entrega = 7;</code>
     */
    private $prazo_entrega = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp validade = 8;</code>
     */
    private $validade = null;
    /**
     * Generated from protobuf field <code>double custo_frete = 9;</code>
     */
    private $custo_frete = 0.0;
    /**
     * Generated from protobuf field <code>double preco_frete = 10;</code>
     */
    private $preco_frete = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $oferta
     *     @type string $cnpj
     *     @type string $logotipo
     *     @type string $nome
     *     @type string $servico
     *     @type \Google\Protobuf\StringValue $descricao_servico
     *     @type int $prazo_entrega
     *     @type \Google\Protobuf\Timestamp $validade
     *     @type float $custo_frete
     *     @type float $preco_frete
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Freterapido::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 oferta = 1;</code>
     * @return int|string
     */
    public function getOferta()
    {
        return $this->oferta;
    }

    /**
     * Generated from protobuf field <code>int64 oferta = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOferta($var)
    {
        GPBUtil::checkInt64($var);
        $this->oferta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cnpj = 2;</code>
     * @return string
     */
    public function getCnpj()
    {
        return $this->cnpj;
    }

    /**
     * Generated from protobuf field <code>string cnpj = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCnpj($var)
    {
        GPBUtil::checkString($var, True);
        $this->cnpj = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logotipo = 3;</code>
     * @return string
     */
    public function getLogotipo()
    {
        return $this->logotipo;
    }

    /**
     * Generated from protobuf field <code>string logotipo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLogotipo($var)
    {
        GPBUtil::checkString($var, True);
        $this->logotipo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nome = 4;</code>
     * @return string
     */
    public function getNome()
    {
        return $this->nome;
    }

    /**
     * Generated from protobuf field <code>string nome = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNome($var)
    {
        GPBUtil::checkString($var, True);
        $this->nome = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string servico = 5;</code>
     * @return string
     */
    public function getServico()
    {
        return $this->servico;
    }

    /**
     * Generated from protobuf field <code>string servico = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setServico($var)
    {
        GPBUtil::checkString($var, True);
        $this->servico = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue descricao_servico = 6;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getDescricaoServico()
    {
        return $this->descricao_servico;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue descricao_servico = 6;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setDescricaoServico($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->descricao_servico = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 prazo_entrega = 7;</code>
     * @return int
     */
    public function getPrazoEntrega()
    {
        return $this->prazo_entrega;
    }

    /**
     * Generated from protobuf field <code>int32 prazo_entrega = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setPrazoEntrega($var)
    {
        GPBUtil::checkInt32($var);
        $this->prazo_entrega = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp validade = 8;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getValidade()
    {
        return $this->validade;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp validade = 8;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setValidade($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->validade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double custo_frete = 9;</code>
     * @return float
     */
    public function getCustoFrete()
    {
        return $this->custo_frete;
    }

    /**
     * Generated from protobuf field <code>double custo_frete = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setCustoFrete($var)
    {
        GPBUtil::checkDouble($var);
        $this->custo_frete = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double preco_frete = 10;</code>
     * @return float
     */
    public function getPrecoFrete()
    {
        return $this->preco_frete;
    }

    /**
     * Generated from protobuf field <code>double preco_frete = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setPrecoFrete($var)
    {
        GPBUtil::checkDouble($var);
        $this->preco_frete = $var;

        return $this;
    }

}

