// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: freterapido.proto

#include "freterapido.pb.h"
#include "freterapido.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace freterapido {

static const char* FreteRapido_method_names[] = {
  "/freterapido.FreteRapido/CalcularFrete",
};

std::unique_ptr< FreteRapido::Stub> FreteRapido::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FreteRapido::Stub> stub(new FreteRapido::Stub(channel));
  return stub;
}

FreteRapido::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CalcularFrete_(FreteRapido_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FreteRapido::Stub::CalcularFrete(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::freterapido::CalcularFreteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CalcularFrete_, context, request, response);
}

void FreteRapido::Stub::experimental_async::CalcularFrete(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CalcularFrete_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::freterapido::CalcularFreteResponse>* FreteRapido::Stub::AsyncCalcularFreteRaw(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::freterapido::CalcularFreteResponse>::Create(channel_.get(), cq, rpcmethod_CalcularFrete_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::freterapido::CalcularFreteResponse>* FreteRapido::Stub::PrepareAsyncCalcularFreteRaw(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::freterapido::CalcularFreteResponse>::Create(channel_.get(), cq, rpcmethod_CalcularFrete_, context, request, false);
}

FreteRapido::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FreteRapido_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FreteRapido::Service, ::freterapido::CalcularFreteRequest, ::freterapido::CalcularFreteResponse>(
          std::mem_fn(&FreteRapido::Service::CalcularFrete), this)));
}

FreteRapido::Service::~Service() {
}

::grpc::Status FreteRapido::Service::CalcularFrete(::grpc::ServerContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace freterapido

