// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: freterapido.proto
#ifndef GRPC_freterapido_2eproto__INCLUDED
#define GRPC_freterapido_2eproto__INCLUDED

#include "freterapido.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace freterapido {

class FreteRapido final {
 public:
  static constexpr char const* service_full_name() {
    return "freterapido.FreteRapido";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CalcularFrete(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::freterapido::CalcularFreteResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::freterapido::CalcularFreteResponse>> AsyncCalcularFrete(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::freterapido::CalcularFreteResponse>>(AsyncCalcularFreteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::freterapido::CalcularFreteResponse>> PrepareAsyncCalcularFrete(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::freterapido::CalcularFreteResponse>>(PrepareAsyncCalcularFreteRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void CalcularFrete(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::freterapido::CalcularFreteResponse>* AsyncCalcularFreteRaw(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::freterapido::CalcularFreteResponse>* PrepareAsyncCalcularFreteRaw(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status CalcularFrete(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::freterapido::CalcularFreteResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::freterapido::CalcularFreteResponse>> AsyncCalcularFrete(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::freterapido::CalcularFreteResponse>>(AsyncCalcularFreteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::freterapido::CalcularFreteResponse>> PrepareAsyncCalcularFrete(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::freterapido::CalcularFreteResponse>>(PrepareAsyncCalcularFreteRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void CalcularFrete(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::freterapido::CalcularFreteResponse>* AsyncCalcularFreteRaw(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::freterapido::CalcularFreteResponse>* PrepareAsyncCalcularFreteRaw(::grpc::ClientContext* context, const ::freterapido::CalcularFreteRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CalcularFrete_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CalcularFrete(::grpc::ServerContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CalcularFrete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_CalcularFrete() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CalcularFrete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalcularFrete(::grpc::ServerContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalcularFrete(::grpc::ServerContext* context, ::freterapido::CalcularFreteRequest* request, ::grpc::ServerAsyncResponseWriter< ::freterapido::CalcularFreteResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CalcularFrete<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_CalcularFrete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_CalcularFrete() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::freterapido::CalcularFreteRequest, ::freterapido::CalcularFreteResponse>(
          [this](::grpc::ServerContext* context,
                 const ::freterapido::CalcularFreteRequest* request,
                 ::freterapido::CalcularFreteResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->CalcularFrete(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_CalcularFrete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalcularFrete(::grpc::ServerContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void CalcularFrete(::grpc::ServerContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_CalcularFrete<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CalcularFrete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_CalcularFrete() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CalcularFrete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalcularFrete(::grpc::ServerContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CalcularFrete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_CalcularFrete() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CalcularFrete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalcularFrete(::grpc::ServerContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalcularFrete(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_CalcularFrete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_CalcularFrete() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->CalcularFrete(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_CalcularFrete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalcularFrete(::grpc::ServerContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void CalcularFrete(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CalcularFrete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_CalcularFrete() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::freterapido::CalcularFreteRequest, ::freterapido::CalcularFreteResponse>(std::bind(&WithStreamedUnaryMethod_CalcularFrete<BaseClass>::StreamedCalcularFrete, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_CalcularFrete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CalcularFrete(::grpc::ServerContext* context, const ::freterapido::CalcularFreteRequest* request, ::freterapido::CalcularFreteResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCalcularFrete(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::freterapido::CalcularFreteRequest,::freterapido::CalcularFreteResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CalcularFrete<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CalcularFrete<Service > StreamedService;
};

}  // namespace freterapido


#endif  // GRPC_freterapido_2eproto__INCLUDED
